- Dockerfile
Signed-off-by: Itxaka <igarcia@suse.com>
> verify signatures coming from cos packages

- docs/content/_index.md
Fixed a couple of typos in _index.md.
Nic
> fix typos in documentation

- .github/workflows/release-arm.yaml
- earthly.sh
Added docker.socket to mounts
Removed the push from the Build step so push can push
Removed the if check since the whole job only runs on tag
> Update build command and docker.socket

- internal/agent/hooks/gruboptions.go
- internal/agent/hooks/hook.go
- internal/agent/hooks/lifecycle.go
- internal/agent/hooks/runstage.go
- internal/agent/install.go
- pkg/config/config.go
- tests/assets/autoinstall.yaml
- tests/autoinstall_test.go
- tests/upgrade_latest_cli_test.go
- tests/upgrade_latest_k8s_test.go
This changeset add boot options to the installation configuration. Also slightly extends the current tests to check back if the parameters was set.
Fixes https://github.com/c3os-io/c3os/issues/100
> :sparkles: Boot options

- .github/workflows/image.yaml
Signed-off-by: vipsharm <sharma.vipin@gmail.com>
> Enable ubuntu to test pipelines

- docs/content/quickstart/installation.md
- docs/content/upgrade/kubernetes.md
Fixes: https://github.com/kairos-io/kairos/issues/137
> :memo: Add note on how to upgrade from c3os

- Earthfile
- overlay/files-iso/boot/grub2/grub.cfg
- repositories/repositories.yaml
- repositories/repositories.yaml.fedora
- repositories/repositories.yaml.rockylinux
- repositories/repositories.yaml.tumbleweed
- repositories/repositories.yaml.ubuntu
This changeset adds Secure boot support.
QA Checklist:
> :lock: Secure boot

- internal/agent/install.go
- internal/agent/reset.go
- sdk/bus/events.go
This should allow to hook to the reset event
> :sparkles: Add reset event for sdk

- docs/content/reference/networking.md
Thanks to @christianprim for the examples!
> :memo: Add network bonding docs

- .circleci/config.yml
- .github/workflows/image.yaml
- .github/workflows/release.yaml
- Earthfile
- go.mod
- go.sum
- images/Dockerfile.fedora
- images/Dockerfile.rockylinux
- tests/tests_suite_test.go
This changes makes Fedora and Rockylinux bootable, altough there are still issues with them (tty doesn't work, installation fails)
> :penguin: Make fedora/rockylinux to boot

- docs/src/pages/quickstart/installation.mdx
- docs/src/pages/reference/configuration.md
- docs/src/pages/upgrade/kubernetes.mdx
Signed-off-by: Lucas Ramage <lucas.ramage@infinite-omicron.com>
> Fix typo in quickstart install doc

- docs/src/pages/installation/raspberry.md
- docs/src/pages/quickstart/installation.mdx
**What this PR does / why we need it**: Fixes some typos and adds blocksize to dd command
> :memo: Docs/enhancements

- images/Dockerfile.opensuse-arm-rpi
- overlay/files-opensuse-arm-rpi/etc/cos/bootargs.cfg
- overlay/files/etc/cos/bootargs.cfg
**What this PR does / why we need it**: Several enhancements:
- Uniforms networking into ARM images, adds `rd.ifnames=1`
- Adds `wpa_supplicant` to openSUSE ARM images
> :penguin: ARM enhancements

- docs/src/pages/installation/automated.md
Simplifies steps in the osbuilder docs. Tested locally
> :memo: Update osbuilder docs

- docs/src/pages/architecture/container.md
> :memo: Expand on container-based design

- docs/src/pages/installation/raspberry.md
> :memo: Update ARM instructions

- docs/src/pages/installation/takeover.md
> :memo: Update takeover instructions to use latest images

- overlay/files/etc/dracut.conf.d/99-kairos.conf
- overlay/files/etc/systemd/network/21-dhcp-legacy.network
> :gear: Configure dhcp for legacy named ifaces (eth*)

- tests/autoinstall_test.go
> :robot: Add grubmenu check test

- docs/src/pages/installation/raspberry.md
Signed-off-by: antongisli <anton@huge.geek.nz>
simple text changes for language
Fixes #
> 📖 Update raspberry.md

- CONTRIBUTING.md
Adds :penguin: , :robot:, :arrow_up: icons to contributing
> :book: Update contributing icons

- .github/run_test.sh
master builds are currently failing
> :robot: Fix ginkgo deps in install_test

- .github/workflows/bump_repos.yml
> :robot: Add signoff to autobump workflow

- docs/src/pages/advanced/after-install.mdx
- docs/src/pages/reference/configuration.md
> :book: Add docs to configure additional system users

- Earthfile
> :penguin: Use ubuntu kernel with alpine flavor

- .github/ISSUE_TEMPLATE/release.md
- README.md
- docs/src/pages/quickstart/index.mdx
**What this PR does / why we need it**: Cleanups the front page README and removes redundant content as it is already in the welcome page of our docs. Also updates our release checklist
> :book: Cleanup README and point to documentation welcome page

- .github/ISSUE_TEMPLATE/config.yml
this forces to use templates when opening issues and provide useful links
> :book: Add ISSUE_TEMPLATE config file

- Earthfile
Signed-off-by: Ettore Di Giacinto <mudler@kairos.io>
Fixes #
> :penguin: Keep openSUSE kernel on RPI

- docs/src/pages/advanced/build.mdx
- docs/src/pages/architecture/container.md
- docs/src/pages/architecture/immutable.md
- docs/src/pages/installation/automated.md
- docs/src/pages/quickstart/index.mdx
> :book: Add advanced/build section

- docs/src/pages/installation/automated.md
> :book: Restore example

- CONTRIBUTING.md
Fixes comment here: https://github.com/kairos-io/kairos/pull/381#issuecomment-1303239807
> Update CONTRIBUTING.md to explain DCO

- docs/src/pages/advanced/build.mdx
- docs/src/pages/quickstart/index.mdx
> :book: Expand on netbooting artifacts and consuming raw images locally

- docs/src/pages/installation/raspberry.md
> example shell script to locally create customized disk image 

- docs/content/en/docs/Advanced/livelayering.md
> :book: Remove duplicated header

- Earthfile
- pkg/machine/machine.go
- repositories/repositories.yaml
- sdk/system/grub.go
**What this PR does / why we need it**: Alpine currently fails booting, this set of changes fixes boot and also drops workarounds
Fixes #
> :arrow_up: Bump repository and drop some workarounds

- .github/workflows/release-arm.yaml
- docs/content/en/docs/Installation/p2p.md
- docs/content/en/docs/Installation/raspberry.md
- docs/content/en/docs/Reference/image_matrix.md
> :seedling: Don't build image files for arm, just container images

- .github/workflows/release-arm.yaml
> :seedling: Keep building, stop releasing

- Earthfile
- overlay/files/etc/dracut.conf.d/99-kairos.conf
- overlay/files/etc/systemd/network/20-dhcp.network
- overlay/files/etc/systemd/network/21-dhcp-legacy.network
- repositories/repositories.yaml
Those are now shipped with the dracut packages, separately. It also fixes #443 by adding systemd-resolved/networkd to the initrd coming from our repo
Signed-off-by: Ettore Di Giacinto <mudler@kairos.io>
Need first https://github.com/kairos-io/packages/pull/59
Fixes #443
> :seedling: Drop moved files

- docs/content/en/docs/Reference/configuration.md
Signed-off-by: Ettore Di Giacinto <mudler@kairos.io>
Point raise in the github discussions in https://github.com/kairos-io/kairos/discussions/447
> :book: Add debugging tips for cloud-config files

- docs/content/en/docs/Reference/reset.md
> :book: Add remote reset examples

- overlay/files/system/oem/11_persistency.yaml
- overlay/files/system/oem/25_default_paths.yaml
> Fixes 472. Added /var/snap to the list of persistent mount points.

- Earthfile
- scripts/netboot.sh
> :seedling: Ipxe fixes

- scripts/start_vm_qemu.sh
> Use kvm when running qemu to make things faster

- docs/content/en/docs/Reference/build.md
> :book: Add from scratch advanced build docs

- pkg/config/config.go
- pkg/config/config_test.go
Fixes: https://github.com/kairos-io/kairos/issues/491
> :bug: Preserve header when fetching config via URL

- overlay/files/system/oem/28_cgroups.yaml
> :penguin: Set default hybrid cgroups for alpine

- docs/content/en/docs/Architecture/container.md
This fixes broken links in the documentation.
> docs: fix broken link to manual and kubernetes upgrade

- docs/content/en/docs/Reference/configuration.md
Signed-off-by: Ognian <Ognian@users.noreply.github.com>
Fixes #
> k3s parameter for labeling is --node-label

- docs/content/en/docs/Reference/image_matrix.md
> :book: Clarify Alpine support

- docs/content/en/docs/Reference/image_matrix.md
> :book: Reword top level info block

- docs/content/en/docs/Advanced/networking.md
- docs/content/en/docs/Architecture/network.md
- docs/content/en/docs/Getting started/_index.md
- docs/content/en/docs/Installation/interactive.md
- docs/content/en/docs/Installation/manual.md
- docs/content/en/docs/Installation/p2p.md
- docs/content/en/docs/Installation/takeover.md
- docs/content/en/docs/Reference/configuration.md
- docs/content/en/docs/Reference/faq.md
- docs/content/en/docs/Upgrade/manual.md
> :book: Remove doubled header and add cloud config reference

- docs/README.md
- docs/content/en/docs/Installation/netboot.md
- docs/content/en/docs/Installation/p2p.md
- docs/content/en/docs/Installation/takeover.md
- docs/package-lock.json
- docs/package.json
> :book: Add documentation for network booting

- .github/workflows/image.yaml
- Earthfile
- tests/netboot_test.go
- tests/tests_suite_test.go
> :robot: Netboot testing

- docs/content/en/docs/Getting started/_index.md
Linking the image matrix support page.
Signed-off-by: Saad Malik <simfox3@gmail.com>
- Add a link for documentation
> Add details for image matrix

- sdk/unstructured/suite_test.go
- sdk/unstructured/yaml.go
- sdk/unstructured/yaml_test.go
to be used in: https://github.com/spectrocloud/kubesplit/tree/remove-dependencies
Part of: https://github.com/kairos-io/kairos/issues/515
> Add helper function to unstructured

- docs/content/en/docs/Examples/_index.md
- docs/content/en/docs/Examples/metallb.md
- docs/content/en/docs/Getting started/_index.md
- docs/content/en/docs/Installation/p2p.md
- docs/content/en/docs/Reference/entangle.md
- Adds `entangle` reference docs with runnable examples
- Add full p2p samples
- Add `MetalLB` example
> :book: Update  docs

- docs/content/en/docs/Advanced/build.md
> Add apiVersion to example yaml

- .github/actions/spelling/expect.txt
- docs/content/en/docs/Advanced/customizing.md
- docs/content/en/docs/Installation/automated.md
- docs/content/en/docs/Reference/configuration.md
- docs/content/en/docs/Reference/image_matrix.md
> :book: Rephrase sections

- images/Dockerfile.alpine-opensuse-leap
Signed-off-by: Christian Prim <christian.prim@gmx.ch>
Removes openntpd from Alpine images as it makes some trouble
Fixes #519
> 🐛 Remove openntpd

- .github/actions/spelling/expect.txt
- docs/content/en/docs/Getting started/_index.md
- docs/content/en/docs/Installation/p2p.md
- docs/content/en/docs/_index.md
**What this PR does / why we need it**: It includes docs for #2 
Fixes #
> :book: Update p2p docs, general enhancements

- docs/content/en/docs/Getting started/_index.md
typo corrected
Signed-off-by: Akhilesh Verma <akhlesh.vermaofc@gmail.com>
Fixes #
> typo corrected

- images/Dockerfile.alpine-arm-rpi
Signed-off-by: Christian Prim <christian.prim@gmx.ch>
Port the changes made in the general alpine image to RPi
Fixes #476
> 🐧 Alpine rpi: switch to busybox ntpd and latest tag

- .github/actions/spelling/expect.txt
- docs/config.toml
- docs/content/en/blog/_index.md
- docs/content/en/blog/media-section.md
- docs/content/en/docs/Contribution Guidelines/_index.md
- docs/content/en/docs/Getting started/_index.md
- docs/content/en/docs/Media/_index.md
- docs/content/en/docs/_index.md
- Add media section
- update docsy
- fix issue with duplicated nave menu entry
- remove unexpected tag
- add blog section with first super short post about the new media section
**Which issue(s) this PR fixes** :
Fixes #601
> :book: Add media section to our docs

- images/Dockerfile.fedora
I was encountering issues fetching the github keys because there was no domain resolution
> :bug:  Fedora Configure system-resolved for DNS resolution

- MAINTAINERS.md
Updating MAINTAINERS with new team members as by our GOVERNANCE.md
> :book: Update MAINTAINERS

- docs/content/en/docs/Media/_index.md
It seems like the video was removed and uploaded with a new ID
Fixes #
> Chore update broken youtube video

- Earthfile
- cmd/agent/main.go
- cmd/profile-build/main.go
- internal/common/version.go
Partial fix for kairos-io/kairos#643.
> :seedling: Add version information directly from git

- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/config_test.go
This is part of https://github.com/kairos-io/kairos/issues/399
I need this merged first, so I can use it on the `kcrypt` side. Then I will bump kcrypt here to use the new config pkg.
> Deeply merge yamls in original data

- docs/content/en/docs/Advanced/after-install.md
- docs/content/en/docs/Advanced/build.md
- docs/content/en/docs/_index.md
> Fix: typos

- internal/agent/hooks/kcrypt.go
- pkg/config/config.go
This shouldn't be required anymore. It was useful for testing/POC, but not required.
Fixes #
> :seedling: Drop unrequired copy

- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-22-lts
- overlay/files-ubuntu/etc/default/console-setup
- overlay/files-ubuntu/system/oem/03-setupcon.yaml
To fix the broken QR in ubuntu
Fixes #212
> :bug: Add required font in Ubuntu for QR generation

- .github/workflows/release.yaml
> enable rockylinux for release

- framework-profile.yaml
> :penguin: Add `kcrypt-challenger` to images

- docs/content/en/docs/Getting started/_index.md
- docs/content/en/docs/Installation/webui.md
> :book: Add WebUI section

- CONTRIBUTORS.md
- MAINTAINERS.md
Also link back to MAINTAINERS.md
Fixes: #660
cc: @christianprim, @Ludea, @jbalonso
> :book: Add `christianprim`, `ludea` and `jbalonso` to CONTRIBUTORS.md

- docs/content/en/docs/Advanced/partition_encryption.md
> :book: Update offline encryption image

- internal/webui/public/index.html
**What this PR does / why we need it**
While looking at the codemirror upgrade, I saw that we have this broken dependency because the name and directory structure of the package changed. I don't think there was a major impact but rather have it working properly
none
> :bug: Add broken webui dependency

- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/release.md
- docs/content/en/blog/release-v1.5.md
> :book: Add blog release announcement for v1.5

- images/Dockerfile.alpine-arm-rpi
- images/Dockerfile.alpine-opensuse-leap
- images/Dockerfile.debian
- images/Dockerfile.fedora
- images/Dockerfile.opensuse-leap
- images/Dockerfile.opensuse-leap-arm-rpi
- images/Dockerfile.opensuse-tumbleweed
- images/Dockerfile.opensuse-tumbleweed-arm-rpi
- images/Dockerfile.rockylinux
- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-22-lts
Signed-off-by: Martin Schuessler <1407812+c0ffee@users.noreply.github.com>
Sorted packages in existing dockerfiles
Fixes #786
> :penguin: sorted packages in dockerfiles and removed some duplicates

- docs/content/en/docs/Installation/raspberry.md
> Add correct extension to rasberry pi image

- docs/content/en/docs/Architecture/immutable.md
- docs/content/en/docs/Installation/qrcode.md
- docs/content/en/docs/Reference/faq.md
- docs/content/en/docs/Reference/image_matrix.md
Some improvements to the documentation while working on the FOSDEM presentation.
> :book: Misc improvements to docs

- docs/content/en/blog/Kairos-at-FOSDEM-2023.md
- docs/content/en/blog/media-section.md
- docs/content/en/blog/release-v1.5.md
This blog post includes:
- a summary of the FOSDEM 2023
- suggested talks
- a very short conclusion
Fixes #780
> Add blog post about FOSDEM 2023

- docs/content/en/docs/Development/development.md
> Add dev docs on how to bump packages

- docs/content/en/docs/Installation/automated.md
- docs/content/en/docs/Installation/netboot.md
- docs/content/en/docs/Reference/auroraboot.md
- docs/content/en/docs/Reference/entangle.md
Adds documentation about https://github.com/kairos-io/AuroraBoot, a complete reference and how to use it. It also updates the docs with updated commands on how to use auroraboot instead.
> :book: Add `AuroraBoot` documentation

- docs/content/en/docs/Media/_index.md
> 📖 Add FOSDEM 2023 presentation to media section

- CONTRIBUTORS.md
> :book: Add `sdwilsh` to CONTRIBUTORS.md

- .github/workflows/image.yaml
> :robot: Run some jobs on self-hosted runners

- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-22-lts
In https://github.com/kairos-io/kairos/pull/821 a number of packages were explicitly added that were previously installed automatically.  This change removes some of the more obvious ones that we should not need to install manually.
> 🐧 [ubuntu] Remove some packages that should not be needed

- Earthfile
This is helpful to quickly generate temp images and upload them to ttl.sh plus you can quickly distinguish the images by branch and sha
> :wrench:  Add temp-image Earthly target

- docs/content/en/docs/Reference/auroraboot.md
- examples/auroraboot/master-template.yaml
> :book: Add AuroraBoot pipe example, fix templates examples

- docs/content/en/docs/Getting started/_index.md
Signed-off-by: Geetika Batra <geetikab@vmware.com>
Fixes #
> Added a step to move kairos-cli as kairos

- .github/workflows/bump_repos.yml
- .github/workflows/image-arm.yaml
- .github/workflows/image.yaml
- .github/workflows/lint.yml
- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
- .github/workflows/release_bin.yaml
- .github/workflows/unit-tests.yml
- .yamllint
- Earthfile
This PR adds an Earhtly target to lint the GH workflow yaml files plus it fixes the existing issues
> :wrench: Use yamllint to check lint issues on GH workflows

- docs/content/en/docs/Architecture/network.md
- docs/content/en/docs/Examples/multi-node-p2p-ha-kubevip.md
- docs/content/en/docs/Examples/p2p_e2e.md
- docs/content/en/docs/Installation/p2p.md
- docs/content/en/docs/Media/_index.md
This enhances the p2p docs with the demo content. Will update when the video will be available
Fixes #
> :book: Update p2p documentation

- .github/workflows/schema.yaml
> :robot: Fix schema checker

- Earthfile
Remove the dependency on the hugo docker image (community contributed) and instead use a debian image and install the official release for the currently running architecture.
Fixes #906
> :wrench: Build docs on arm64

- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-22-lts
snapd packages were removed by mistake
Fixes #917
> Re-add snapd packages for ubuntu flavors

- docs/content/en/docs/Reference/image_matrix.md
Needs https://github.com/kairos-io/provider-kairos/pull/241 to be merged
Relates to #766
> :book: Add rocky Linux to support matrix

- docs/content/en/docs/Architecture/meta.md
- docs/content/en/docs/Architecture/network.md
- docs/content/en/docs/Examples/p2p_e2e.md
- docs/content/en/docs/Installation/automated.md
- docs/content/en/docs/Media/_index.md
- docs/content/en/docs/Reference/build.md
**What this PR does / why we need it**: Adds libp2p video to our docs
Fixes #909
Fixes #907
> :book: Add libp2p video, small fixups

- .github/bump_repositories.sh
- .github/test.sh
- Earthfile
- docs/scripts/build.sh
- earthly.sh
- internal/agent/make_art.sh
- scripts/build_vm.sh
- scripts/netboot.sh
- scripts/start_vm_qemu.sh
- scripts/start_vm_vbox.sh
This changes integrates `shellcheck` into the standard lint flow.  Along the way, it also fixes or suppresses any existing issues that exist.
> 🔧 Integrate Shellcheck

- docs/content/en/docs/Development/nvidia.md
> :book: Add reference documentation for Nvidia ARM boards

- pkg/config/config.go
but rather print a Warning.
Fixes #885
Fixes #
> :bug: Don't fail when config_url is not accessible

- docs/content/en/docs/Installation/webui.md
> :book: Fix grammatical syntax on WebUI page

- docs/content/en/docs/Installation/manual.md
> :book: Fix grammatical structure

- .github/workflows/release.yaml
> :robot: Add flavor in the sign step

- docs/static/v1.6.0-rc1/cloud-config.json
- docs/static/v1.6.0-rc2/cloud-config.json
- docs/static/v1.6.0-rc3/cloud-config.json
Adding manually because job failed to do automatically :P see https://github.com/kairos-io/kairos/actions/runs/4270835378
> :book: Add cloud-config.json for v1.6.0 release candidates

- .github/workflows/schema.yaml
Issue: https://github.com/kairos-io/kairos/actions/runs/4274657702/jobs/7441431930
> :wrench: Use ci-robbot to open cloud config schema updates

- docs/static/v1.6.0/cloud-config.json
We still had the issue with the job while 1.6 was released, so adding this one manually too, hopefully it's the last one :crossed_fingers: :stuck_out_tongue:
> :book: Add cloud-config.json for v1.6.0

- internal/agent/hooks/hook.go
With the changes to elemental the elemental cli can now clear content from encrypted partitions.
Fixes #733
> :bug: remove kcrypt hook after reset

- sdk/state/state.go
> :bug: Update state.go (#987

- .github/workflows/image.yaml
- .github/workflows/release.yaml
> :wrench: Upgrade earthly action for nodejs deprecations

- .github/workflows/image-arm.yaml
- .github/workflows/image.yaml
- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
which is now bumped to v2
https://blog.sigstore.dev/cosign-2-0-released/
Fixes #
> :robot: Fix cosign signing

- .github/workflows/image.yaml
- tests/assets/autoinstall.yaml
- tests/assets/config.yaml
- tests/assets/live-overlay.yaml
- tests/assets/qrcode.yaml
- tests/assets/single.yaml
- tests/install_test.go
add a test for this fix: https://github.com/kairos-io/kairos/commit/491dd042d323a2c5403dcd72cf142ffe1ec709fe (merged just the fix after manual QA to unblock the release).
This PR is blocked until this one is merged: https://github.com/kairos-io/kairos/pull/832
The test will be adapted when that happens.
> :robot: Add test for #491dd04

- docs/content/en/docs/Getting started/_index.md
> Update Getting started Index with typo fixes

- Earthfile
> :robot: Use VARIANT, output SBOM to build

- .github/workflows/image-arm.yaml
- .github/workflows/image.yaml
- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
Otherwise we don't have permission to upload security reports
See: https://github.com/github/codeql/issues/8843
> :robot: Update workflow permissions

- cmd/agent/main.go
While working on #687, I noticed that this link is broken. It's a tiny fix which can be merged without waiting for the actual fix of the above-mentioned issue.
> :bug: Fix link to QR code

- Earthfile
> :robot: Add grype scan reports

- .github/workflows/image.yaml
> :robot: Add wildcard also on master workflow

- tests/netboot_test.go
> :robot: Add state check on netboot tests

- .github/workflows/image-arm.yaml
- .github/workflows/release-arm.yaml
We were missing the -P flag
Fixes #
> :robot: Fix ARM builds

- go.mod
- go.sum
version 1.0.0 wont run all stages in certains cases
Fixes #
> :bug: Bump yip

- Earthfile
> :robot: Pin trivy version

- pkg/config/schemas/users_schema_test.go
Groups changed and unit tests were not passing
This was masked by the unit-tests being broken
Fixes #
> :robot: Fix users schema test

- framework-profile.yaml
artifacts are now provided via the grub2-efi package directly
Fixes #
> :sparkles: Drop system/shim package

- .github/workflows/image-arm.yaml
- .github/workflows/release-arm.yaml
> :robot: Drop -P when calling earthly from the script

- docs/content/en/docs/Upgrade/kubernetes.md
> Update kubernetes.md: fix typo

- docs/content/en/blog/kairos-canonical.md
> :book: Add collaboration announcement blog post

- docs/config.toml
- pkg/config/config.go
> :book: Add newsletter link in community section

- images/Dockerfile.ubuntu-20-lts
> Removed redundant kernel install

- images/Dockerfile.ubuntu-22-lts
> Removed redunant kernel install

- framework-profile.yaml
- overlay/files/system/oem/11_persistency.yaml
- tests/install_test.go
Fixes https://github.com/kairos-io/kairos/issues/1172
> :arrow_up: Bump repositories

- .github/workflows/release-arm.yaml
- docs/content/en/docs/Reference/image_matrix.md
Start uploading arm images to their own repo
relates to #770
> :robot: Push arm images in their own repo with img suffix

- .github/workflows/release-arm.yaml
Fixes the sarif dir under release workflow
Partially fixes https://github.com/kairos-io/kairos/issues/1200
> :robot: Copy sarif files from proper folder

- .github/workflows/image-arm.yaml
- .github/workflows/image.yaml
- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
> :robot: Attach and sign SBOM

- .github/workflows/image-arm.yaml
- .github/workflows/image.yaml
- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
> Revert ":robot: Attach and sign SBOM"

- framework-profile.yaml
Signed-off-by: Itxaka <itxaka.garcia@spectrocloud.com>
Fixes #
> Remove dracut/kcrypt

- .github/workflows/image.yaml
> :robot: Disable push from Earthly for master

- .github/workflows/release_bin.yaml
- .goreleaser.yaml
- Earthfile
Pass the version to goreleaser, so the artifact that can be dowloaded includes it
relates to #1249
> :robot: Add version to goreleaser

- internal/webui/webui.go
The collector is stricter with the files it reads and requires that they have proper extension to be considered. This PR adds the yaml extension to the temporary file created by the webUI
relates to #1255
> :bug: Add yaml extension to temp file created by webui

- pkg/config/collector/collector.go
- pkg/config/collector/collector_test.go
- pkg/config/config.go
- pkg/config/schemas/root_schema_test.go
**What this PR does / why we need it**:R
White list options that can be added in the cmdline
relates to #1255
> :bug: Do not merge all cmdline arguments to generic config

- .goreleaser.yaml
- Earthfile
Since the code is built on v2, the VERSION to build it needs to also have v2 in the path
fixes #1287
> Pass VERSION flag including v2 in path

- docs/content/en/blog/release-v2.0.md
On hold until we have artifacts
> :book: v2.0 Announcement blog post

- docs/content/en/blog/release-v2.0.md
The comma just gets in the URL, so it goes 404!
Fixes #
> :book: Fix immucore link

- .github/workflows/image-arm.yaml
- Earthfile
Generates arm64 generic isos able to run under qemu emulation
Fixes #790
> :seedling: Generic arm64 isos

- .github/workflows/image-arm.yaml
This should build and push the arm-generic artifacts to the repo on master merge
Fixes #
> :robot: Push arm64 generic artifacts to quay on master merge

- README.md
- docs/content/en/blog/sena-architecture.md
- docs/scripts/build.sh
Fixes https://github.com/kairos-io/kairos/issues/1014
> :book: SENA whitepaper announcement

- .github/workflows/image-arm.yaml
- .github/workflows/release-arm.yaml
- Earthfile
> :robot: Release arm generic artifacts on release

- docs/content/en/docs/Upgrade/manual.md
> :book: Docs for upgrade with auth

- CONTRIBUTORS.md
https://github.com/kairos-io/kairos/pull/1296
> Add https://github.com/scuzhanglei to contributors

- pkg/github/releases_test.go
Leftover broken tests for releases functions
Fixes #1345
> :robot: Fix releases test

- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-22-lts
Looks like this packages were installed as a dep of other packages, but now nothing brings them.
Lets be explicit with the packages we want :D
Fixes #
> :bug: Re-add editor packages to ubuntu flavors

- Earthfile
> :robot: Allow building agent from branches

- Earthfile
> :robot: Allow testing kcrypt from branches

- framework-profile.yaml
- tests/tests_suite_test.go
> :robot: :arrow_up: Use latest agent and fix install tests 

- .github/encryption-tests.sh
- .github/workflows/image.yaml
- Earthfile
- profile-build/go.sum
- tests/assets/autoinstall.yaml
- tests/assets/encryption/challenger-patch.yaml
- tests/assets/encryption/challenger-server-ingress.template.yaml
- tests/assets/encryption/cluster-issuer.yaml
- tests/assets/encryption/kustomization.yaml
- tests/encryption_test.go
- tests/tests_suite_test.go
> :robot: Add encryption tests

- Earthfile
> :bug: Remove duplication of kairos vars in os-release

- CONTRIBUTORS.md
> Add c0ffee to the contributors list

- .github/workflows/release-arm.yaml
This is an attempt to fix release pipelines failures: https://github.com/kairos-io/kairos/actions/runs/5089099753/jobs/9149531881
> :robot: disable parallelism on arm self-hosted release builds

- .github/workflows/release-arm.yaml
> :robot: run release-arm build on self-hosted

- .github/workflows/image.yaml
- Earthfile
- Only build iso+image
- Only upload sarif and sboms on master merge
- Do not upload anything but ISO on PRs
- Only upload iso+image+sarif+sbom on master merge
Fixes #1445
> :robot: Improve CI PR building

- .github/workflows/image.yaml
- Earthfile
> :robot: Fix building security scans on master

- .github/ISSUE_TEMPLATE/release.md
> :book: Update release template

- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin
- images/Dockerfile.ubuntu-20-lts-arm-rpi
- images/Dockerfile.ubuntu-22-lts
- images/Dockerfile.ubuntu-22-lts-arm-rpi
- images/Dockerfile.ubuntu-arm-rpi
> Removing unattended-upgrade from ubuntu images

- CONTRIBUTORS.md
> :book: Add Andreas Reitz to contributors 

- overlay/files-iso/boot/grub2/grub.cfg
Some had vga some didnt
Fixes #
> :seedling: Sync all kairos entries in livecd

- .github/flavors.json
- Earthfile
- framework-profile.yaml
- images/Dockerfile.almalinux
- images/Dockerfile.fedora
- images/Dockerfile.rockylinux
> :penguin: Add AlmaLinux flavor

- images/Dockerfile.almalinux
- images/Dockerfile.alpine-arm-rpi
- images/Dockerfile.alpine-opensuse-leap
- images/Dockerfile.debian
- images/Dockerfile.fedora
- images/Dockerfile.opensuse-leap
- images/Dockerfile.opensuse-leap-arm-rpi
- images/Dockerfile.opensuse-tumbleweed
- images/Dockerfile.opensuse-tumbleweed-arm-rpi
- images/Dockerfile.rockylinux
- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin
- images/Dockerfile.ubuntu-20-lts-arm-rpi
- images/Dockerfile.ubuntu-22-lts
- images/Dockerfile.ubuntu-22-lts-arm-rpi
- images/Dockerfile.ubuntu-arm-rpi
> :sparkles: Sort packages and remove duplicates

- images/Dockerfile.almalinux
- images/Dockerfile.debian
- images/Dockerfile.fedora
- images/Dockerfile.rockylinux
- images/Dockerfile.ubuntu
- images/Dockerfile.ubuntu-20-lts
- images/Dockerfile.ubuntu-22-lts
> :bug: Add qemu-guest-agent to images that are missing it

- examples/byoi/ubuntu-fips/README.md
It is useful to give some commands to check out if we are actually running with fips or not
> :book: Update FIPS example with testing commands

- .github/flavors.json
- framework-profile.yaml
This is an attempt to have generic FIPS images
Related to : #362
> :seedling: Add fips-generic framework image

- Earthfile
This is not really needed for this repo but for consistency purposes
> Keep distro calculation in sync with provider repo

- Earthfile
fixes the current issue with building arm on master
> :robot: Add missing targetarch argument

- .github/workflows/image-arm.yaml
Otherwise it cannot get the commit message
Fixes #
> :robot: Add fetch to notify action under arm

- Earthfile
> Fix k3s installation when a version is passed

- .github/workflows/release.yaml
> :robot: Make spac on release workers

- .github/repo-diff-msg.sh
https://www.shellcheck.net/wiki/SC2028
https://www.shellcheck.net/wiki/SC2129
https://www.shellcheck.net/wiki/SC2005
> Fix linting errors

- Earthfile
because there is no shell there
Fixes #
> Don't run command on scratch images

- .github/flavors-arm.json
> :bug: Add missing standard arm rpi flavors

- Earthfile
- framework-profile.yaml
> Install the right k3s package based on the init system

- examples/cloud-configs/wifi.yaml
Fixes https://github.com/kairos-io/kairos/issues/1729
Co-authored-by: @jbalonso
> :book: Add wifi example

- Earthfile
For ease of testing installation stuff
Has a target that allows to build an EFI only ISO for uki testing
Fixes #
> :sparkles: Build uki iso artifacts

- framework-profile.yaml
bundles/kairos-overlay-files is now static/kairos-overlay-files
Fixes #
> :arrow_up: Bump repos and change layout package category

- Earthfile
- images/Dockerfile.ubuntu
Maybe this is not the right solution, but just want to get the ball rolling to talk about which one is
Fixes #1849
> Do not remove cache dir

- images/Dockerfile.alpine
This allows building generic isos with alpine flavor
Fixes #1895
> :bug: Do not install grub-bios on arm64 alpine dockerfile

- images/Dockerfile.alpine
Signed-off-by: Itxaka <itxaka@kairos.io>
(cherry picked from commit 566f1b8c17d0f60f5bd93ca5bd1697c04b8912e7)
Fixes #
> Fix alpine dockerfile

- .github/flavors.json
- .github/workflows/image-arm-pr.yaml
couple of issues that the alpine patch brougth
Fixes #
> :robot: Fix leftovers from alpine PR

- .github/workflows/image.yaml
> :robot: Fix image workflow

- .github/workflows/image.yaml
> Lint yaml indentation

- .github/workflows/image-pr.yaml
- .github/workflows/image.yaml
- Earthfile
Signed-off-by: Itxaka <itxaka@kairos.io>
Fixes #
> 🤖 Drop uki test as its no longer valid

- images/Dockerfile.debian
for some reason the CDN mirrors are not working
> Fix debian repository

- images/Dockerfile.debian
Otherwise we cannot pull form any added repos
Fixes #
> :bug: Install ca-certificates on debian base image first

- Earthfile
> Fix download path for ipxe

- .github/workflows/release.yaml
- .github/workflows/reusable-upgrade-latest-test.yaml
- Earthfile
> :bug: Fix arch name in arm artifacts

- tests/provider_upgrade_k8s_test.go
This is just an atempt to make this test a bit less brittle on master. It seems like sometimes the runners are very slow so the test fails despite it doing what it is supposed to.
Here's an example break:
Test loops here for 30 mins
```
version = v2.4.3-rc3-1-gd7ce4d5-k3s1.28.2+1
version = v2.4.3-rc3-1-gd7ce4d5-k3s1.28.2+1
version = v2.4.3-rc3-1-gd7ce4d5-k3s1.28.2+1
version = v2.4.3-rc3-1-gd7ce4d5-k3s1.28.2+1
version = v2.4.3-rc3-1-gd7ce4d5-k3s1.28.2+1
```
But it was still creating the container
```
system-upgrade   apply-os-upgrade-on-localhost-with-fad084049055ae593e39b8-nnb8w   0/1     ContainerCreating   0          11s
```
> Add extra time to upgrade test

- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-build-provider.yaml
- Earthfile
- images/Dockerfile.debian
- images/Dockerfile.kairos
- images/Dockerfile.kairos-alpine
- images/Dockerfile.kairos-debian
- images/Dockerfile.kairos-opensuse
- images/Dockerfile.kairos-rhel
- images/Dockerfile.kairos-ubuntu
- images/Dockerfile.ubuntu
> Use base (cached) images on master

- .github/flavors.json
- .github/workflows/image-arm-pr.yaml
- .github/workflows/image-pr.yaml
- .github/workflows/image.yaml
> Update alpine to 3.19

- .github/workflows/reusable-build-base-image.yaml
When originally created I copy pasted the setup for nvidia, so the name of the files said nvidia even when it wasn't the case. This improves the readability of the pipeline.
> Minor improvement for changed files names

- .github/workflows/release-arm.yaml
> Also sign `-img` images

- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-build-provider.yaml
- .github/workflows/reusable-docker-arm-build.yaml
- .github/workflows/reusable-encryption-test.yaml
- .github/workflows/reusable-image-and-iso-arm-generic.yaml
- .github/workflows/reusable-install-test.yaml
- .github/workflows/reusable-provider-tests.yaml
- .github/workflows/reusable-qemu-acceptance-test.yaml
- .github/workflows/reusable-qemu-bundles-test.yaml
- .github/workflows/reusable-qemu-reset-test.yaml
- .github/workflows/reusable-upgrade-latest-test.yaml
- .github/workflows/reusable-upgrade-with-cli-test.yaml
- .github/workflows/reusable-zfs-test.yaml
- .github/workflows/uki.yaml
> upgrade upload and download actions at the same time

- Earthfile
to consume newer kairos-agent that has this fix:
https://github.com/kairos-io/kairos-sdk/commit/f665d930e2ff994320c3cd3fc9b7744207f214fc
Fixes #
> Bump kairos-framework

- .github/ISSUE_TEMPLATE/release.md
> Update the release ticket template

- Earthfile
Consuming the named arguments
Fixes #2174
> Update enki to v0.0.9

- Earthfile
to get this change:
https://github.com/kairos-io/kcrypt-challenger/pull/45
Fixes #2087
> Bump kairos framework

- Earthfile
> bump framework to 2.4.6 to use its cache

- Earthfile
This allows passing random flags to enki like `--cmdline` so its easier to produce custom entries directly from the target
Fixes #
> :robot: Allow passing flags to enki and bump version

- .github/workflows/reusable-upgrade-latest-test.yaml
- Earthfile
> Bump framework and osbuilder

- examples/byoi/fedora/README.md
> Add warning to outdated example

- Earthfile
- images/Dockerfile.kairos
- images/Dockerfile.kairos-alpine
- images/Dockerfile.kairos-debian
- images/Dockerfile.kairos-opensuse
- images/Dockerfile.kairos-rhel
- images/Dockerfile.kairos-ubuntu
> Move versioneer call inside Dockerfile

- .github/workflows/reusable-build-provider.yaml
> append k3s version to master builds

- images/Dockerfile.kairos-ubuntu
- images/Dockerfile.ubuntu
Meant to fix https://github.com/kairos-io/kairos/actions/runs/7963195786/job/21757030745
> Have different compression depending on the ubuntu release

- Earthfile
> Bump framework to use compressed binaries

- tests/tests_suite_test.go
- tests/uki_test.go
> Fix uki test

- .github/ISSUE_TEMPLATE/release.md
so we don't forget when releasing
> Add docs versioning item in the template

- Earthfile
> Bump framework to v2.7.17

- .github/workflows/uki.yaml
> :robot: Run fedora and ubuntu uki tests

- images/Dockerfile.rhel
```
260M -rwxr-xr-x 1 root root 260M Mar 19 15:26 /efi/EFI/kairos/active.efi
```
> Reduce fedora uki image size

- .github/workflows/uki_branches.yaml
Should allow us to manually test different agent and immucore branches for uki jobs directly and run the tests batteries with artifacts built from those branches so we dont need to cut a newer version just to test something
Fixes #
> :robot: Allow manual testing of branches for uki jobs

- Earthfile
Fixes issue with bootentry for UKI
Fixes #
> Bump framework to v2.7.22

- .github/workflows/release.yaml
- .github/workflows/uki.yaml
- .github/workflows/uki_branches.yaml
> Generate keys while building uki ISOs

- .github/flavors.json
- .github/workflows/image.yaml
- .github/workflows/uki.yaml
- .github/workflows/uki_branches.yaml
> Bump fedora from 38 to 39

- Earthfile
> Bump framework

- Earthfile
Fixes https://github.com/kairos-io/kairos/issues/1456
Fixes #
> Allow https protocol in ipxe

- .github/workflows/uki.yaml
> Produce 24.04 uki master artifact

- .github/workflows/reusable-docker-arm-build.yaml
this is so we can offer a master build artifact for Nvidia or other arm images
relates to https://github.com/kairos-io/kairos/issues/2467
> Push master ARM images to quay

- images/Dockerfile.nvidia
https://github.com/kairos-io/kairos/issues/2467
> fix(orin): disable ISCSI in the initramfs generation

- examples/byoi/ubuntu-non-hwe/README.md
fix a typo: `asume`->`assume`
Fixes #
> :book: chore: fix typos

- .github/flavors.json
- images/Dockerfile.kairos-ubuntu
- images/Dockerfile.ubuntu
> Add ubuntu 24.04 arm generic

- .github/flavors.json
- .github/workflows/image.yaml
- .github/workflows/uki.yaml
- .github/workflows/uki_branches.yaml
- images/Dockerfile.kairos-rhel
- images/Dockerfile.rhel
> :penguin: Bump to Fedora 40

- .github/workflows/uki_branches.yaml
> :robot: Fix reusable uki master test

- Earthfile
This was a lot simpler than when the ticket was originally created thanks to us moving the logic to the Dockerfiles 🎉 
fixes #1759
> Remove double brackets from Earthly

- Earthfile
> bump framework to v2.8.3

- Earthfile
> bump framework to v2.8.4

- tests/provider_decentralized_test.go
- tests/provider_install_qrcode_test.go
- tests/provider_upgrade_k8s_test.go
- tests/provider_upgrade_latest_k8s_test.go
caused by https://github.com/kairos-io/kairos/pull/2623
> Update matching text for latest systemd tests

- README.md
> Add clomonitor badge

- .github/workflows/scorecards.yaml
- renovate.json
Track tests go.mod file
Pin stuff to digests when possible
> :robot: Improve renovate

- Earthfile
- renovate.json
> Get digests from earthfile

- Earthfile
> Remove leftover

- .github/workflows/reusable-uki-test.yaml
- Earthfile
Brings latest osbuilder which has the pure golang ukifier
> :wrench: : Update to use new osbuilder

- Earthfile
Bump osbuilder and fix fedora uki (and probably ubuntu) by not breaking hardlinks
Fixes #
> :wrench: Bump osbuilder

- .snyk
> Add .snyk config

- Earthfile
> Bump framework to 2.9.0 to get newer dependencies

- .github/workflows/image.yaml
missed this one when changing the permissions, hopefully it's the only one 🙏
> Add missing permissions on master pipeline

- .github/workflows/reusable-encryption-test.yaml
Looks like the VM is running out of resources when running, so move the tests to our KVM workers and limit the cpu/memory for the VM
Fixes #2715
> Run encryption tests in KVM nodes

- tests/provider_upgrade_k8s_test.go
> Allow for pre-releases on the upgrade test

- .github/flavors.json
- .github/workflows/image-pr.yaml
- .github/workflows/image.yaml
> comment release matcher in tests

- Earthfile
> Bump framework to v2.10.2

- .github/flavors.json
- images/Dockerfile.kairos-ubuntu
- images/Dockerfile.ubuntu
> Remove ubuntu 23.10 from the pipelines

- .github/flavors.json
- .github/workflows/image-arm-pr.yaml
- .github/workflows/release-arm.yaml
> Run arm jobs under arm workers

- .github/ISSUE_TEMPLATE/release.md
until we can fix the automated test
Fixes #2770
> Add manual test for edgevpn setup

- Earthfile
I'm not sure why it worked in the past or why relative paths are ok but generating a sarif file locally and uploading it to https://sarifweb.azurewebsites.net/Validation
shows that the version generated by this commit is valid, while the old one was not:
Fixes #
> Generate relative paths to files

- .github/workflows/reusable-docker-arm-build.yaml
> :robot: Make arm64 workers use docker mirror

- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-docker-arm-build.yaml
as suggested here:
https://github.com/github/codeql-action/issues/2476#issuecomment-2350277932
Fixes #
> Split the uploading of trivy and grype results

- .github/workflows/image.yaml
- Earthfile
- tests/reset_test.go
> :arrow_up: Bump framework

- images/Dockerfile.nvidia
> :bug: Add missing binary to nvidia images

- .github/flavors.json
- .github/workflows/uki.yaml
> :robot: Fix flavors

- Earthfile
- tests/assets/suc.yaml
- tests/provider_upgrade_k8s_test.go
- tests/provider_upgrade_latest_k8s_test.go
- tests/tests_suite_test.go
Bring a more updated kairos version and set the version from the test, instead of hardcoded
Fixes #
> :robot: Fix upgrade k8s test

- .github/workflows/release.yaml
- .github/workflows/reusable-uki-test.yaml
- Earthfile
because enki is now archived
Fixes #
> Remove enki references from the Earthfile and pipelines

- Earthfile
> Bump framework to 2.14.5

- Earthfile
> Bump framework to downgrade k3s to non-rc versions

- images/Dockerfile.nvidia
> fix(nvidia): bump cuda to 12.6

- images/Dockerfile.nvidia
> fix(nvidia): run with DEBIAN_FRONTEND=noninteractive

- images/Dockerfile.nvidia
> feat(nvidia): add nvidia-l4t-kernel-oot-modules

- .github/workflows/image-arm.yaml
https://github.com/kairos-io/kairos/actions/runs/12687897629/job/35363289989#step:8:8
> Install agent to use in generic arm workflow

- images/Dockerfile.kairos-rhel
- images/Dockerfile.rhel
> Support building arm64 rhel images

- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-docker-arm-build.yaml
Part of: https://github.com/kairos-io/kairos/issues/3119
Fixes #
> Split security scan categories to make it easier to navigate

- .github/workflows/reusable-build-flavor.yaml
Fixes https://github.com/kairos-io/kairos/issues/3133
Fixes #
> Check scan results and upload them too

- .github/flavors.json
> Use github runners to build arm artifacts

- .github/workflows/reusable-docker-arm-build.yaml
We are not building raw images for it so the build dir is empty
Fixes #
> Do not upload artifacts for rpi3

- .github/workflows/reusable-docker-arm-build.yaml
Unfortunately duplicated here: https://github.com/kairos-io/kairos/blob/bd1dacc2ed019623b0ce917a62c921efda787d83/Earthfile#L11
Fixes #
> Set the FRAMEWORK_VERSION build arg in arm builds

- CODE_OF_CONDUCT.md
We already have a code of conduct in the community repo, adding this just to reference to it since we advertise this repo as our main one
> Reference code of conduct

- Earthfile
> Bump framework fixes k3s-agent args issue

- .github/workflows/reusable-qemu-acceptance-test.yaml
> Simplify test job and use kvm

- Earthfile
> fix(nvidia): point to the new script

- .github/workflows/image-master-arm.yaml
- .github/workflows/image-master.yaml
- .github/workflows/image-pr-arm.yaml
- .github/workflows/image-pr.yaml
- tests/autoinstall_test.go
- tests/encryption_test.go
- tests/install_target_test.go
For PR and Master builds we dont need to build a full set of extra things
Fixes #
> Build less arm artifacts

- .github/workflows/image-master-arm.yaml
- .github/workflows/image-master.yaml
- .github/workflows/image-pr-arm.yaml
- .github/workflows/image-pr.yaml
- .github/workflows/release.yaml
- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-qemu-test.yaml
- .github/workflows/reusable-uki-test.yaml
- tests/assets/bundles.yaml
- tests/bundles_test.go
- tests/provider_upgrade_k8s_test.go
With a expires by, it will expire after 6 hours and its more stable than ttl
Fixes #
> Move temp images to quay

- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-release.yaml
- images/Dockerfile
so it's controlled on the kairos side
Fixes #
> Pass framework version to kairos init

- .github/workflows/image-master.yaml
- .github/workflows/image-pr.yaml
- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-encryption-test.yaml
- .github/workflows/reusable-qemu-netboot-test.yaml
- .github/workflows/reusable-qemu-test.yaml
> Allow to have different k8s distro images for testing

- .github/workflows/image-master-arm.yaml
> Drop tj changed files and use a simple script

- examples/keylime/README.md
- tests/assets/sysext/README.md
fix some typos in comment
Fixes #
> chore: fix some typos in comment

- renovate.json
> Pin actions to digest

- .github/workflows/upload-cloud-images.yaml
https://github.com/aws-actions/configure-aws-credentials#OIDC
https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
Part of: https://github.com/kairos-io/kairos/issues/3262
Fixes #
> Implement OIDC auth flow for aws

- images/Dockerfile
> Bump kairos-init and framework

- .github/public-cloud/cleanup-old-images-gcp.sh
- .github/public-cloud/test-gcp-image.sh
- .github/public-cloud/upload-image-to-gcp.sh
Part of https://github.com/kairos-io/kairos/issues/3175
Fixes https://github.com/kairos-io/kairos/issues/3175
> 3175 add gcp smoke test

- .github/public-cloud/test-azure-image.sh
- .github/public-cloud/upload-image-to-azure.sh
- .github/workflows/upload-cloud-images.yaml
Part of: https://github.com/kairos-io/kairos/issues/3175
(implements the Azure part, the rest are done)
Fixes #
> 3175 test azure

- .github/workflows/image-master.yaml
- tests/provider_decentralized_test.go
> Re-enable decentralized test

- .github/workflows/image-master-arm.yaml
- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-qemu-netboot-test.yaml
- .github/workflows/reusable-qemu-test.yaml
- .github/workflows/reusable-uki-test.yaml
- tests/assets/kairos.ipxe
- use arm worker to build nvidia base image
- set model in the image tag for reusable tests
Fixes #
> Improve test jobs

- .github/workflows/reusable-release.yaml
> Revert ":arrow_up: Update softprops/action-gh-release action to v2.2.2"

- .github/workflows/reusable-build-flavor.yaml
- .github/workflows/reusable-release.yaml
> Add grype critical check with details

- .github/workflows/reusable-uki-test.yaml
> Add grype detail check to uki as well

- .grype.yaml
> Bump debian kernel ignores for grype

- .github/workflows/reusable-uki-test.yaml
- examples/builds/fedora-fips/Dockerfile
- examples/builds/rockylinux-fips/Dockerfile
- examples/builds/ubuntu-fips/Dockerfile
- examples/builds/ubuntu-non-hwe/Dockerfile
- images/Dockerfile
supersedes https://github.com/kairos-io/kairos/pull/3412
> Bump kairos-init and AuroraBoot

- .github/workflows/stale.yaml
> feat(ci): add stale bot

- images/Dockerfile
> Bump to init 0.5.3

- images/Dockerfile
> Bump kairos-init to v0.5.6

- images/Dockerfile
> Bumo init to 0.5.18
