kairos-io/kairos

docs/config.toml, docs/content/_index.md, docs/content/after_install/recovery_mode.md, docs/content/after_install/upgrades.md, docs/content/basics/cli.md, docs/content/basics/layout.md, docs/content/installation/configuration.md, docs/content/installation/device_pairing.md, docs/content/installation/takeover.md
This pr changes all cOS I could find to element.
The old cOS links are dead as of 13.06.2022 and the README.md states
https://github.com/c3os-io/c3os/blob/c83a3466f97514c79069ce32d5e6617d40cd8f44/README.md?plain=1#L20-L22
=> Changed docs from cOS to Elemental

build.sh
Trying to run `./build.sh` at the office, I quickly found out that building from behind a proxy didn't work.
This fixes that as long as the `https_proxy`, `http_proxy` and `no_proxy` environment variables are set appropriately for the environment where the build is performed.  Any of these variables can be left unset if not needed.
=> Support builds from behind a proxy

internal/machine/openrc/unit.go
fixes overwriting of k3s.env for Alpine images by using utils.WriteEnv
=> naive attempt at appending to /etc/rancher/k3s/k3s.env

.github/workflows/image-arm.yaml, .github/workflows/image-corelight.yaml, .github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, Earthfile
images now follow `quay.io/c3os/<variant>-<flavor>:<version>`.  Given framework images are only for internal use I did not change their naming schema.
=> swiched image naming scheme

sdk/clusterplugin/config.go
Cloud config is often written in yaml but go-pluggable and c3os do most of their serialization in json.  This was causing the config section of the cluster config to be lost.  I added support for serializing cluster objects as json and yaml.
=> add support for json serialziation of cluster objects

.github/workflows/image.yaml
Reverts c3os-io/c3os#105
cc @vipsharm seems test are failing, disabling for now. better to debug them separately. did you tried the ISO? is it booting?
=> Revert "Enable ubuntu to test pipelines"

.github/workflows/image.yaml, README.md, images/Dockerfile.ubuntu, tests/autoinstall_test.go, tests/upgrade_cli_test.go
The service isn't enabled by default, and /tmp as such is not writeable - also adds corresponding tests.
It adds also upgrade test for the image built - we were not doing it previously here as the test was moved to the kairos provider.
Supersedes #135
=> Enable tmp mount on ubuntu

.github/workflows/image.yaml, tests/machine/vbox.go, tests/reset_test.go
This adds a simple test for the reset mode. 
It actually creates files into `/oem` and the persistent partition and check their existence after issuing a reset. There is much low hanging fruit here, some of the tests needs to be refactored. I've already created some libs to wrap the helpers up, but will do that in a follow-up
=> :robot: Add reset tests

Earthfile
This avoids curl failures, and let cache downloads during the build phase
=> :art: Avoid curl calls and prefer image copy

Earthfile, docs/src/pages/installation/raspberry.md
The images are in compressed with "XZ" but the extension of the images are only ".img". This happened when converting the build system to Earthly. The PR fixes Earthly and the docs accordingly.
=> docs: Correction to Raspberry instructions

internal/agent/config.go, internal/agent/install.go, internal/agent/recovery.go, internal/agent/reset.go
I added a setting to the agent configuration to skip the sleeps.  In the context of a user interaction the sleeps make sense however if a user has additional plugins that automate all aspects of configuration the sleeps are not needed.
=> added support for fast mode

images/Dockerfile.opensuse, images/Dockerfile.opensuse-arm-rpi, overlay/files/system/oem/05_network.yaml
This should make uniform all systemd-based flavors network settings, by adopting systemd-networkd - no specific tests needed as the suite runs over SSH and node is expected to bring up network automatically
=> :sparkles: Switch to systemd-networkd on systemd-based flavors

.github/workflows/image.yaml, Earthfile, examples/bundle/Dockerfile, internal/agent/agent.go, internal/agent/hooks/bundles.go, internal/agent/hooks/gruboptions.go, internal/agent/hooks/hook.go, pkg/config/config.go, pkg/machine/file.go, pkg/machine/partitions.go, tests/assets/live-overlay.yaml, tests/bundles_test.go
This adds the `bundles` list also into the `install` block. This has the effect that bundles here specified are run after-install before first-boot. 
Note: bundles should install things either to `/usr/local` or run custom container/code. In this phase `/usr/local` and `/oem` are accessible.
=> :sparkles: Add bundles to post-install hooks

overlay/files-iso/boot/grub2/grub.cfg, overlay/files/etc/cos/bootargs.cfg
added net.ifnames=1 to kernel params.
Signed-off-by: vipsharm <sharma.vipin@gmail.com>
=> Fixing the interface names across OS flavors

.github/workflows/release.yaml, Earthfile, overlay/files-fedora/etc/cos/bootargs.cfg, overlay/files/system/oem/26_selinux.yaml
SELinux support have to be handled separately in https://github.com/kairos-io/kairos/issues/114. fedora based version has selinux, which is enabled by default but we don't have support for it yet.
Fixes #63 . Now fedora installs and boots correctly afterwards
=> :penguin: Disable temporarly SELinux on fedora

Earthfile, internal/agent/hooks/hook.go, internal/agent/hooks/kcrypt.go, pkg/config/config.go
This adds the https://github.com/kairos-io/kcrypt dracut module and the binary to the images.
This allows to manually call `kcrypt` after installation on already existing partitions. Can be used also after-deployment to encrypt partitions with `kcrypt encrypt PARTITION_LABEL`.
Note: it requires a discovery plugin to handle encryption. it has to be located under `/system/discovery/kcrypt-discovery-<plugin_name>`
During installation, it can be specified in the yaml of the node config as such:
```yaml
install:
encrypted_partitions:
- LABEL
```
Related to https://github.com/kairos-io/kairos/issues/184
=> :sparkles: Add kcrypt to images

.github/workflows/image.yaml, .github/workflows/release.yaml, Earthfile, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts
this PR refactor the ubuntu images final location:
- ubuntu 22.04 as `quay.io/kairos/core-ubuntu-22-lts`
- ubuntu 20.04 (currently published as `ubuntu`)   as `quay.io/kairos/core-ubuntu-20-lts`
- ubuntu latest (currently published as `ubuntu-rolling`)  as `quay.io/kairos/core-ubuntu`
See also https://github.com/kairos-io/kairos/issues/150#issuecomment-1272909504.
It also adds the Ubuntu 22.04 LTS image.
=> :penguin: Change ubuntu images location

.github/run_test.sh, Earthfile, go.mod, go.sum
New version of ginkgo introduces an arg that breaks the CLI. we previously were installing always latest which was differing from the version pinned in the go.mod. This change sets up the runner of the tests to install ginkgo declared in the go.mod file.
=> :robot: Install ginkgo pinned from go.mod

overlay/files/etc/cos/bootargs.cfg
Boot assessment would take care of falling back, so reboot by default
=> :sparkles: Re-enforce active/passive boot strategy

.circleci/config.yml, .github/workflows/image.yaml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml, Earthfile, images/Dockerfile.opensuse, images/Dockerfile.opensuse-arm-rpi, overlay/files/etc/dracut.conf.d/99-kairos.conf, overlay/files/etc/systemd/network/20-dhcp.network, overlay/files/system/oem/05_network.yaml
This PR:
- Drops wicked references from openSUSE images
- Adds systemd-networkd settings to initramfs
=> Drop wicked, long live to systemd-networkd

overlay/files/system/oem/11_persistency.yaml
This change is in accordance with the support for the kubeadm provider.
=> ✨ Added /etc/kubernetes to persistent path list

docs/src/pages/architecture/container.md
In the architecture/container section of the documentation, the http link pointing to the automated installation page is incorrect, there's a leading slash missing.
Nic
=> change the automated installation http link in container.md page to correctly point to the automated installation page

overlay/files/etc/cos/bootargs.cfg, tests/autoinstall_test.go
**What this PR does / why we need it**: Enhance current test suites to check basic configuration (dracut module enabled, boot assessment) and adds default bootargs to reboot the machine automatically in case active/passive is not booting to handle automatic fallback
=> :robot: Enhance test coverage

cmd/agent/main.go, internal/agent/agent.go, internal/agent/hooks/bundles.go, internal/agent/hooks/gruboptions.go, internal/agent/hooks/hook.go, pkg/config/config.go, sdk/state/machine.go, sdk/state/state.go, sdk/system/cloudconfig.go, tests/autoinstall_test.go
**What this PR does / why we need it**: 
- Avoids to add '.' as a query prefix to state api
- Adds recovery to state api
- Adds cloudconfig SDK commands to add cloud configs in runtime
- Refactors hook so that they use the same interface - a different set is used for firstboot and the sentinel file for bundles has changed to a more generic name
=> :sparkles: enhancements

.gitignore, cmd/agent/main.go, internal/agent/install.go, internal/agent/reset.go, internal/agent/upgrade.go, pkg/config/config.go, pkg/utils/env.go
What this PR does / why we need it:
Adds support for elemental process to have access to env variables set in Config.Install.Env in reset
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes https://github.com/kairos-io/kairos/issues/259
linking the earlier PR here [260](https://github.com/kairos-io/kairos/pull/260)
=> ✨ add env to config to use across all stages 

internal/agent/install.go
This is a small refactoring that shows an error when a config file can't be loaded from the system due to an error.
=> :art: Enhance error handling

images/Dockerfile.alpine
**What this PR does / why we need it**: Add bonding/bridge packages to core images (see https://wiki.alpinelinux.org/wiki/Bonding )
=> :penguin: Add bonding and bridge to alpine x86_64 images

images/Dockerfile.opensuse, images/Dockerfile.opensuse-arm-rpi
**What this PR does / why we need it**: Adds polkit to openSUSE images. polkit is used by hostnamed to set hostname with systemd-networkd.
**Which issue(s) this PR fixes** :
Fixes #280
=> :penguin: Add polkit to openSUSE images

overlay/files/system/oem/25_default_paths.yaml, tests/autoinstall_test.go
**What this PR does / why we need it**: This has the purpose to create default paths that are needed by the rootfs in order to be overlayed correctly by the initramfs. Note this is a workaround until a better solution with #210 is found, which manipulates directly the initramfs configuration for the mounts
Fixes #292
=> :bug: Add default_path oem file

Earthfile
The PR upgrades luet to version 0.33.0
this version of luet reads proxy variables for environment.
=> :arrow_up: update luet version to 0.33.0

images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts
**What this PR does / why we need it**: This PR adds iptables and conntrack tools to ubuntu images. This is needed as a requirement of kubeadm to deploy k8s clusters using provider.
=> ✨ add iptables and conntrack to ubuntu images

internal/agent/agent.go
This PR sets the env variables passed in the config on agent start so that sub processes/cmds triggered by kairos agent will have access to the environment variables through os.Environ()
Ex: If the proxy vars are passed in config env, then setting the environment variable will allow luet to have access to the set env variables.
=> set env vars in agent

overlay/files/system/oem/21_grub.yaml
During resets otherwise the state gets pruned - this means the additional grub menu entries get lost
Fixes #
=> :gear: Update grubmenu during reset and upgrade

.gitattributes, .gitignore, CONTRIBUTING.md, earthly.ps1, go.mod, go.sum
Adds additional Windows desktop support to the project. 
If anyone finds this later by searching, please note this was on win11 with docker for desktop. If you install earthly.exe to your PATH everything works fine if you do `earthly +test` in powershell if you want to try different versions of earthly. The ps1 will pin the specific version of earthly kairos is currently using and testing against in CI and runs all commands in a linux container.
fixes issues with wsl when you try running .sh. default checkouts with git for windows will let windows manage the eol and set everything to CRLF. When you try and run .sh you get the following.
```
ubuntu@DESKTOP-F54SPNC:/mnt/c/Users/luthe/kairos/kairos$ ./earthly.sh
-bash: ./earthly.sh: /bin/bash^M: bad interpreter: No such file or directory
``` …
=> :seedling: Add Better Windows Desktop Support to Kairos

overlay/files/system/oem/11_persistency.yaml, overlay/files/system/oem/27_harderning.yaml, tests/autoinstall_test.go, tests/reset_test.go
**What this PR does / why we need it**: Otherwise config paths permissions are dependant on the rootfs. This configuration make sure permissions are correctly set even if the rootfs doesn't set the proper bits
=> :seedling: Harden config path and make sure are not rootfs-dependant

images/Dockerfile.alpine
Signed-off-by: Justin Barksdale <3pings@users.noreply.github.com>
Open VM Tools is installed but it is not enabled.  This PR will enable open-vm-tools on boot.
Fixes # N/A
=> 🐛  Enable Open VM Tools on boot

images/Dockerfile.alpine, overlay/files/system/oem/26_vm.yaml
**What this PR does / why we need it**: Fixes master failures, and besides avoid to have all services enabled on boot, but dynamically loaded depending on the activation context.
=> :seedling: Start vmtools/qemu-useragent if we run on VMs

overlay/files/system/oem/21_kcrypt.yaml, tests/autoinstall_test.go
**What this PR does / why we need it**: It runs the hook only if there is a OEM partition accessible. It uses the state api to get the state and the device name programmatically
Fixes #358
=> :bug: Do not run kcrypt hook without a oem mount

overlay/files/system/oem/11_persistency.yaml
Typically _update-ca-certificates_ is executed to update the list of root CA certificates.  update-ca-certificates reads the added source certificates from _/usr/share/pki/trust, /usr/share/pki/trust/anchors_ and updates the files in _/var/lib/ca-certificates and /etc/ssl/certs_
=> ✨ directories added to support - update-ca-certificates

internal/agent/upgrade.go
If not release was specified, the code picked the first one returned by the provider which was not the latest. We now choose the last one. In combination with [this PR](https://github.com/kairos-io/provider-kairos/pull/77/files), it should now be the latest release.
This PR is also asks the user for confirmation. We could add a new flag `no-prompt` or something like that, to avoid the confirmation dialog but:
- we already have a `force` flag which will may confuse users on which one does what
- the code needs refactoring to avoid passing boolean arguments to functions (quite some of them actually)
Maybe it's not worth the effort and we should skip the confirmation altogether?
Fixes #249
=> Upgrade to latest release if one is not specified and ask user to confirm

images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts, overlay/files/system/oem/11_persistency.yaml, overlay/files/system/oem/25_default_paths.yaml
Note: This is creating snap folders for all flavors (`/var/lib/snap` and `/snapd`) - I'd prefer we inject persistent paths if we detect snapd but we don't have #210 yet, so it would get quite hairy. Once we get #210 we can get back at that and programmatically add mount points/paths if we detect bins
Fixes #401
=> :penguin: Add support for snapd

docs/content/en/docs/Installation/automated.md
Docs show quay.io/kairos/osbuilder-tools:v0.1.1, which no longer works all that well and will send the user down a rabbit hole of many wasted hours. Updating to :latest tag. 
Signed-off-by: Fred Loucks <77683877+cybernetic-mountaineer@users.noreply.github.com>
Fixes #
=> :book: Switch to "latest" tag for osbuilder-tools

internal/agent/agent.go, internal/agent/config.go, internal/agent/install.go, internal/cmd/utils.go, pkg/config/config.go, pkg/config/config_test.go, pkg/machine/bootcmdline.go, pkg/machine/bootcmdline_test.go, pkg/machine/machine.go, pkg/machine/openrc/unit.go, pkg/machine/systemd/unit.go, pkg/utils/sh.go, sdk/bundles/bundle_test.go, sdk/bundles/bundles.go, sdk/profile/build.go, sdk/state/state.go, sdk/system/cloudconfig.go, tests/install_test.go, tests/tests_suite_test.go
Recently we have upgraded to Go 1.19 in #318. The `io/ioutil` package has been deprecated in Go 1.16 (See https://pkg.go.dev/io/ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`
=> :art: Move from io/ioutil to io and os packages

Earthfile
This occasionally leads to errors when repos are not available online, and now this should be also not necessary anymore.
=> :robot: No need to download jq and docker anymore

docs/content/en/docs/Reference/configuration.md
I took this snippet as sample for my config and it took me a while that although I changed config from cloud-config to initramfs/networg stage with different syntax, I copied the wrong group name all the time.. :)
Signed-off-by: Stefan Le Breton <stelb@users.noreply.github.com>
documentation bug
Fixes #
=> admin group is admin not admins

overlay/files-alpine/system/oem/23_rootfs.yaml, pkg/utils/system.go, tests/autoinstall_test.go
Since this is not handled in the boot process, we do this in our devoted file to setup the rootfs configuration. It also adds an e2e test to verify that the mounts are correctly set
Signed-off-by: Ettore Di Giacinto <mudler@kairos.io>
Fixes #440 
Thanks @christianprim for the finding!
=> :bug: Setup / as shared mount on alpine

pkg/config/config.go, pkg/config/config_test.go, sdk/unstructured/yaml.go
This allows to read all the configs found during scanning - this is especially useful in first boot as it allows to have separate config file logic split into several files
**What this PR does / why we need it**: Fixes up failures in https://github.com/kairos-io/provider-kairos/pull/103
=> :seedling: Glob all configs found

overlay/files/system/oem/29_blacklist.yaml
Fixes #277. We are not building our own kernel at the moment - and we can't either build everything in alpine yet. For the moment we can just disable until we have vanilla kernels from #116  which would allow us to cross-build.
Thanks to @christianprim for the investigation and the workaround.
=> :bug: Blacklist bpfilter in Alpine

Earthfile
The netboot target didn't had a default bound to the detected version, if nothing was specified it would result in an empty artifact.
Fixes: #501
=> :bug: Correctly detect default version in netboot

docs/content/en/docs/Installation/automated.md
Signed-off-by: Alexander Bauer <sasha@linux.com>
**What this PR does / why we need it**: Fixes incorrect `cloud_config.yaml` path in `docs -> Installation -> Automated -> ISO Remastering`
=> :book: Adjust documented cloud_config.yaml path for ISO remastering

pkg/config/config.go, pkg/config/config_test.go, tests/autoinstall_test.go
Regression introduced in https://github.com/kairos-io/kairos/pull/502. Also files like .lst were incorrectly included inside /oem/90_custom.yaml
=> :bug: Process only cloud configs

README.md
The link before was pointing to a "quickstart" page, which I couldn't find in the new docs. I thought the "getting started" page was a good substitute, but it could also be linked to the home of the documentation, or even something else. Let me know what you think.
=> :book: Fix link pointing to missing documentation

sdk/clusterplugin/config.go
adds support for proxy and cacert attributes to be set which then can be used by the provider to set the values explicitly.
[Fixes #](https://github.com/kairos-io/kairos/issues/555)
=> ✨  add env and cacerts attributes to clusterplugin.cluster object

cmd/agent/main.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/options.go
**What this PR does / why we need it**: This PR allows to programmatically retrieve the node configuration from the CLI. For instance, in a Kairos node with k3s enabled would behave:
```
$ kairos-agent config get k3s.enabled
true
$ kairos-agent config get k3s
enabled: true`
```
I'm trying to create bundles that extend the system by reading the main configuration file. I want a consolidated way to programmatically access it via commands (either that coming from cloud configs, or bundle themselves). In this way bundles can extend the main config file, keeping one-file-only strategy.
=> :seedling: Return configuration data from the agent

.github/actions/spelling/expect.txt, docs/content/en/docs/Getting started/_index.md
Just some improvements after having gone through the quick start
- Put in tabs the different types of machines in and how to boot on them. Bare-metal and qemu for now, can be extended with more hypervisors in the future
- Rename baremetal with bare-metal
- Add an alert for the user to be aware about the disk space needed in the prerequisites
- update the version of the iso in the example (the previous one was causing some permissions errors)
- some rewording
=> :book: extend quick start with qemu

.github/actions/spelling/excludes.txt
**What this PR does / why we need it**: Otherwise any new PR from renovate would be signaled as invalid, and we grow our includes with hashes
=> :robot: Exclude go.mod from spelling checker

images/Dockerfile.rockylinux
**What this PR does / why we need it**: Currently CI is red on rockylinux. Seems now curl-minimal is shipped in the base image, previously we were installing `curl` and now are conflicting
=> :bug: Fix rockylinux build, curl-minimal is already shipped

pkg/utils/sh.go, sdk/bundles/bundles.go
**What this PR does / why we need it**: This is not _needed_, however, when running bundles we expect the context where we run to be where the bundle was extracted (this reduce verbosity when creating entrypoint scripts for bundles)
=> :seedling: Keep current dir when installing runnable bundles

images/Dockerfile.alpine-opensuse-leap
`busybox-initscripts` was removed from alpine v3.17 and mostly replaced with `busybox-openrc`.
Signed-off-by: Christian Prim <christian.prim@gmx.ch>
Keep up with the latest alpine images.
Fixes #
=> 🐧 Upgrade Alpine to latest Tag

.gitignore, images/Dockerfile.rockylinux, overlay/files-iso/boot/grub2/grub.cfg
Adapts Rocky Linux image so it properly mounts the tmp partition and installs and runs systemd-resolved so dns resolution is working.
Fixes #64
=> :penguin: Rocky Linux

docs/content/en/docs/Installation/manual.md, docs/content/en/docs/Reference/configuration.md
Leftover from the transition, kairos block is called p2p now
Less confusion on docs
Fixes #680
=> :book: Rename references from kairos to p2p

tests/tests_suite_test.go
Allow preseving the VM used for testing:
- speed up tests locally
- debug issues when needed
- increase contributor\developer happiness :smiley: 
**Which issue(s) this PR fixes** 
Fixes #685
=> :seedling: Add option to preserve the VM used for testing

.github/workflows/image.yaml
The test with kubo was failing because there's a version check done by `systemd-sysext` and it didn't match. The issue comes from the new way of fetching the version from git, which in the build step we use the full history and tags so it will look something like `v1.2.3-sha-dirty` while in the `qemu-bundles-tests` we fetch only the last commit without tags or history so it looks just like `sha`. 
Let's make master green again!
=> Adapt CI to match version generation between build and qemu-bundles-tests steps

cmd/agent/main.go, docs/content/en/docs/Upgrade/manual.md, pkg/utils/strings.go
The list of possible releases when doing an upgrade is duplicated
relates to  #684
=> :bug: Remove duplicated list of upgradable releases

CONTRIBUTING.md
Some features we add are actually for maintainers\developers. Hence, a :wrench: icon is a better than :sparkels: or :seedling:
=> Add a new category for commits and PR - toolings

tests/tests_suite_test.go
Allow adding more CPU and RAM for the test machine. This improves perfomance of tests.
You can now run the suite with the following command to create a test VM with more CPUs and RAM:
```
MEMORY=9048 CPU=4 ISO=.../kairos/kairos-...iso CREATE_VM=true  ginkgo run tests/
```
Fix #689
=> :seedling: test VM configure RAM and CPUs

docs/content/en/docs/Advanced/livelayering.md, docs/content/en/docs/Advanced/networking.md, docs/content/en/docs/Installation/automated.md, internal/agent/install.go, internal/agent/interactive_install.go
We have still traces of  `#node-config` that causes confusion among our users, this tries to be consistent by dropping the last reference (I cound find)
=> :seedling: Drop references to node-config

images/Dockerfile.ubuntu-20-lts
Signed-off-by: Justin Barksdale <3pings@users.noreply.github.com>
Adding lldpd and snmpd packages to base image for lldp support.  LLDP allows us to gather attributes about the location of a device as an example without hardcoding details into images individually.
=> :penguin: Added support for lldp

images/Dockerfile.ubuntu-22-lts
Signed-off-by: Justin Barksdale [3pings@users.noreply.github.com](mailto:3pings@users.noreply.github.com)
What this PR does / why we need it:
Adding lldpd and snmpd packages to base image for lldp support. LLDP allows us to gather attributes about the location of a device as an example without hardcoding details into images individually.
=> 🐧 Added lldp support

internal/agent/hooks/hook.go, internal/agent/install.go, internal/agent/reset.go
During reset, we might need to re-apply some deployment logic, such as `kcrypt` to re-encrypt partitions, but others might benefit from this as well. This PR adds reset hooks, and also changes the name of the default one to fit properly the usage in the code.
=> :sparkles: Add reset hook

images/Dockerfile.debian, images/Dockerfile.opensuse-leap, images/Dockerfile.opensuse-leap-arm-rpi, images/Dockerfile.opensuse-tumbleweed, images/Dockerfile.opensuse-tumbleweed-arm-rpi, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts
Providers, or downstream images should add it instead
This needs a PR in provider-kairos, to add it in there instead. Potential fix for #265
=> :penguin: Remove nohang from core images

internal/webui/public/package-lock.json, internal/webui/public/package.json
Reverts kairos-io/kairos#610
The upgrade is a bit trickier than expected and I don't want to block a release because of it so I thought it would be better to revert while I look into it
Fixes #732
=> Revert "Update dependency codemirror to v6"

.github/workflows/release_bin.yaml
Deps now require at least go 1.18
Bumps go version used in the release job
Fixes #740
=> Bump go version for goreleaser job

docs/content/en/docs/Reference/image_matrix.md
**What this PR does / why we need it**:  Corrected the URL of the kairos tumbleweed rpi images
Fixes #758
=> :book: fixed url for kairos tumbleweed rpi images

.github/workflows/image.yaml
On the download release action we only need to download the opensuse-leap artifacts for the subsequent tests. Otherwise we are downloading the whole release with all the artifacts for no reason.
Fixes #756
=> :robot: Only download needed release

docs/content/en/docs/Reference/image_matrix.md
We recently added Rocky Linux and Debian but they are not reflected in the documentation Image Matrix.
n/a
=> Add Rocky Linux and Debian to docs matrix

Earthfile
Looks like a ] was missing and instead of crashing and burning, earthly continued happily, which meant that on v1.5.0 ARM tumbleweed images the initrd is missing as earthly failed to parse the check but did not errored out.
Fixes #784
=> :bug: Fix wrong IF line in Earthfile

scripts/start_vm_qemu.sh
This is similar to what happens when we create a VM with Vbox or with the Test suite.
Useful for developers who test with qemu.
Use with:
```
$ PORT_FORWARD=8222 ./scripts/start_vm_qemu.sh build/kairos.iso
```
When the machine is running you can then do:
```
$ ssh -l kairos -p 8222 127.0.0.1:8882
\# login with password kairos
```
=> :🔧: Allow port forwarding for qemu script

.earthlyignore, .github/workflows/image.yaml
We need to add .earthlyfile to enhance build speed locally. Without this we are sending a lot of unneeded
files to buildkit, especially true for large ISOs under build/.
Fixes #693
=> 🔧 Add earthlyignore file

.github/workflows/image.yaml
Fix for `sed: 1: ".earthlyignore": invalid command code .` in MacOS builds.
See 
In https://github.com/kairos-io/kairos/actions/runs/4072936610/jobs/7017039370
I believe that Mac's sed does not accept the syntax I used.
=> 🔧 sed != gsed in MacOS

sdk/bundles/bundles.go
bundles.RunBundles currently does not support reading image tar files from the filesystem and unpacking it into target location. This PR adds support for it.
Fixes #799 
Depends on - https://github.com/mudler/luet/pull/318 this PR also being merged.
And also the luet dependency will need to be updated.
=> ✨ unpack local image file

images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts
Ubuntu flavors were missing the polkitd service so systemd-networkd was not able to send the set-hostname command to systemd-hostnamed due to permissions.
Also once that was fixed, the system defaulted to the localhost.localdomain static name.
This patch add the polkitd package to ubuntu flavors and removes the existing /etc/hostname file which prevents systemd-networkd from setting the hostname via dhcp
Partially #280
=> :bug: Fix dhcp not able to set hostname

overlay/files/system/oem/31_polkit.yaml
Due to a bug on earthly it seems that some of the directories for polkitd are not being copied under the proper user. This results into polkit not being able to read the dir properly and the rules that come with it.
This patch works around it by installing an oem file that wil restore the proper ownership of those dirs
Partial #280
=> :bug: Fix ownership of polkitd rules dir

images/Dockerfile.debian, images/Dockerfile.fedora, images/Dockerfile.rockylinux, overlay/files/system/oem/31_polkit.yaml
Add missing polkit package for fedora/debia/rockylinux
Also remove the extra /etc/hostname that we were bringing from the base container for debian which prevented setting a transient name
Partial #280 
Needs https://github.com/kairos-io/kairos/pull/805
=> 🐛 Missing polkit packages and extra /etc/hostname files

Earthfile
Space gained is negligible, just a few Kbs usually (with gzip as its currently) but the speed up improvements in building the ISO are really good, for 20 seconds to 40 seconds per ISO build, and that gets more accentuated on CI runs where the runners are more CPU constrained.
=> :penguin: Disable squasfs compression for ISO building

.github/workflows/image.yaml, Earthfile, docs/content/en/docs/Advanced/customizing.md, docs/content/en/docs/Reference/configuration.md, internal/agent/hooks/hook.go, internal/agent/hooks/mounts.go, overlay/files/system/oem/11_persistency.yaml, pkg/config/config.go, tests/custom_mount_test.go, tests/install_test.go, tests/tests_suite_test.go
Users can now specify custom and ephemeral mounts in cloud-init under the `install` section, e.g.:
```
users:
- name: kairos
...
install:
auto: true
device: "auto"
bind_mounts:
- /mnt/bind1
- /mnt/bind2
ephemeral_mounts:
- /mnt/ephemeral
- /mnt/ephemeral2
...
```
Ephemeral mounts are mounted as RW - but changes are discarded when the machine is restart.
Bind mounts will persist changes after restarted.
This is a fix for #210
Fixes #
=> :sparkles: custom user bind and ephemeral mounts

.github/workflows/image.yaml, internal/agent/install.go, tests/install_test.go
**What this PR does / why we need it**: Attempt to fix #781 by making the test explicit. we do run the install manually, so no need to specify automatic installation in the cloud configs. That is tested by autoinstall tests (https://github.com/kairos-io/kairos/blob/master/tests/assets/autoinstall.yaml)
Fixes #781
=> :robot: Don't run installation twice on installation tests

images/Dockerfile.debian
In the logs for debian images, `dracut` provides this warning:
```
dracut: *** Creating image file '/boot/initrd-6.1.0-3-amd64' ***
dracut: Cannot execute compression command 'xz', falling back to default
dracut: Using auto-determined compression method 'pigz'
```
This change adds `xz-utils` to debian images so that it can use `xz` compression.  This was first discovered during the work in #821.
=> 🐧 `xz` Compress initrd Image

images/Dockerfile.debian, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts
This file is not used by `systemd-networkd`, but these images enable `systemd-networkd`.  This change removes the `RUN` commands since the file should be unused.
This was originally identified in #821.
=> 🐧 Remove `RUN` commands that change `/etc/network/interfaces`

pkg/config/config.go, sdk/bundles/bundles.go
set BundleConfig.LocalFile with BundleOptions passed to bundles.RunBundles.
This is required to modify the target if the file is present locally for extraction.
Fixes #822
=> ✨ set local_file bundleconfig to true if target prefix is file://

framework-profile.yaml
because it prevents legacy network from working.
See also: https://github.com/dracutdevs/dracut/issues/1822
=> :bug: Remove systemd-resolved from initramfs

Earthfile, renovate.json
This change adds support for renovate to be able to update the versions of `quay.io/luet/base`, `golang`, and `hadolint`.
Tested with:
* `docker run --mount type=bind,source=$(pwd)/renovate.json,target=/usr/src/app/renovate.json -it renovate/renovate renovate-config-validator`
* https://regex101.com/r/Ax3iG9/1
=> 🔧 Have renovate manage image versions in `Earthfile`

pkg/config/config.go
because installation continues and there is no indication that something went wrong
=> :seedling: Don't swallow yaml config errors

Earthfile
Now that the config is more than the stock config, and folks are interested in using it more, we should have some automation to verify that the config is valid.
=> Validate renovate config file during lint

renovate.json
This ensures that `earthly.ps1` and `earthly.sh` are using a version of Earthly that is managed with renovate.
Filename regex tested here: https://regex101.com/r/eEtcqU/1
Version regex tested here: https://regex101.com/r/T8T9aL/1
=> 🔧 Manage the version of Earthly with renovate

Earthfile
This should trigger an update in short order as the current version of this image is v0.5.2.
=> 🔧 Mange the version of quay.io/kairos/osbuilder-tools with renovate

sdk/clusterplugin/config.go
To add support in the providers to have a conditional check to load the archive images from the local filesystem to containerd or another other CRI.
Fixes # https://github.com/kairos-io/kairos/issues/858
=> ✨  import the images to any CRI on start from the local filesystem

Earthfile
This isn't being picked up in the dashboard (#310), and it might be because `34` isn't a proper semver.
=> 🔧 Add docker versioning for the `RENOVATE_VERSION`

images/Dockerfile.debian, images/Dockerfile.fedora, images/Dockerfile.rockylinux, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts
This is not something that hadolint checks (yet, see https://github.com/hadolint/hadolint/issues/445), but a good practice anyway.
=> 🐧 Packages in docker files should be on a single line

images/Dockerfile.opensuse-leap
Added support for LLDP
Users wishing to use network attributes like LLDP-MED attributes need LLDP to do this.  This enables LLDP and the dependency packages.
N/A
=> 🐧 Support for LLDP

images/Dockerfile.ubuntu-22-lts
Ubuntu advantage tools allows for users to register their node with Canonical.  Since Snaps are supported this will allow them to enable Live Kernel Patches.
Ubuntu Advantage Tools enables registration with Canonical for support and things like Live Kernel Patches.
N/A
=> 🐧 Install ubuntu-advantage-tools

.github/workflows/image-arm.yaml, Earthfile
The problem was caused because the outer target runs on arm64 but when it gets to the docs target the `USERARCH` was amd64. This change checks also for `MODEL` and in case the `USERARCH` is `linux/arm64` and not just `arm64`
you can see it working properly in this run https://github.com/mauromorales/kairos/actions/runs/4223111756/jobs/7332444446#step:9:1170 (cancelled manually after it passed, so ignore that it is red :tongue: )
=> :bug: Fix job "Push latest ARM images" caused by docs target

.github/workflows/image.yaml
to make the run faster
Part of #771
=> Use KVM on tests that run on self-hosted runners

Earthfile
Currently is done during docker image but it makes no sense, it should be during framework otherwise framework images do not contain the binary
Fixes #777
=> :bug: copy kairos agent during framework build

overlay/files/system/oem/31_hosts.yaml
For debian based distributions, /etc/hosts is present but empty. This is because the file is populated when running the configuration. [1] This PR inserts a record before initramfs so it can be manipulated later on by yip's hostname plugin
[1] https://wiki.debian.org/ConfigPackages
Fixes #887
=> :bug: Add record to hosts file when missing

internal/agent/validate.go, internal/webui/public/index.html, internal/webui/webui.go
This PR integrates the schema validations on the WebUI
[Screencast from 2023-02-21 15-21-29.webm](https://user-images.githubusercontent.com/433958/220372220-2e693032-24be-4de4-8539-18cfe8c5fab8.webm)
**Not included**
This PR does not include the refactoring of the Web UI, neither does it include the values of the other form items besides the pure cloud config and it doesn't block the user from installing if the config is invalid. I thought this was ok since this first release will not enforce the validations
Fixes #779
=> :sparkles: Web UI schema validations

Earthfile, images/Dockerfile.debian, images/Dockerfile.fedora, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-22-lts
**What this PR does / why we need it**: Otherwise EFI installs are broken
See also https://github.com/kairos-io/kairos/issues/949 and https://github.com/kairos-io/kairos/pull/874
=> :bug: Add back gdisk to ubuntu/debian images

.github/workflows/schema.yaml
Forgot to change the ref when I was testing this workflow
=> :wrench: Use master as ref in generate schema workflow

images/Dockerfile.ubuntu-20-lts, images/dracut-broken-iscsi-ubuntu-20.patch
There was an issue with dracut 48 in which the iscsid.socket required fs targets to be ready. On an iso this could lead to a dependency cycle between the dmsquash module setting up the livecd rootfs and the iscsi socket required the initrd-fs to be ready.
This was fixed on dracut 50 and its what this patch brings, dropping the socket dependency on the fs target so it can break the dependency cycle.
This only affect ubuntu 20 lts, and only affects booting from the iso. Alos the issue is random as systemd will decide to break the dependency in a non predictable way by disabling one of the services that conflict, so sometimes it would be the iscsi serviec, which would make the iso boot but sometimes it could be other more important services liek teh …
=> :bug: Backport dracut patch for ubuntu 20 iscsi

docs/content/en/docs/Examples/airgap.md, docs/content/en/docs/Installation/automated.md, docs/content/en/docs/Reference/auroraboot.md
**What this PR does / why we need it**: It adds documentation about the latest `AuroraBoot` features that allows to build ISOs for airgapped installations.
Fixes #938
cc: @areitz86 @vfiftyfive
=> :book: Add airgap docs

.github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, Earthfile
**What this PR does / why we need it**: This PR introduces generated images SBOM to our releases
Part of #51 
This PR introduces https://github.com/anchore/syft generating a SBOM which is attached at the end of the image build process. It also adds the SBOM to the uploaded artifacts (jobs and releases)
Example generated SBOM files: [core-debian-v1.6.0-14-g193c740-dirty-sbom.s.zip](https://github.com/kairos-io/kairos/files/10863881/core-debian-v1.6.0-14-g193c740-dirty-sbom.s.zip)
=> :robot: Add SBOM artifacts to CI pipelines

.github/workflows/image-arm.yaml, .github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, Earthfile
This PR attaches sarif scan reports to Github actions (see: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github) allowing to assess security components in the "Security tab". It also adds the reports to the release and attaches to the build results
Part of: https://github.com/kairos-io/kairos/issues/115
=> :robot: Attach trivy scan reports

.github/workflows/image.yaml
Those jobs are small (typically runs for 4/5mins) and might be useful to re-use the cache in such case which makes it faster. This is a test - It is also better probably to free some slots, as no other jobs depends on the fw images.
=> :robot: Run framework build on self-hosted

.github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml
Fixes failures affecting master builds: https://github.com/kairos-io/kairos/actions/runs/4321817792/jobs/7543494120
=> :robot: Use sudo to move generated sarif files

.github/workflows/image.yaml, Earthfile
We were listing on a dir that now doesn't exist necessarly anymore, and when picking up the iso from latest release, we are selectively picking one flavor for the upgrade test.
=> :robot: Fixup test targets

images/Dockerfile.opensuse-tumbleweed-arm-rpi
Those should not be required, and seem were dropped from the openSUSE repositories too.
CI logs: https://github.com/kairos-io/kairos/actions/runs/4327767275/jobs/7581273754
=> :penguin: Drop removed packages from opensuse-tumbleweed-arm-rpi

images/Dockerfile.debian, tests/autoinstall_test.go
**What this PR does / why we need it**: We were missing `systemd-resolved`, thus the symlink was not available
Fixes #1035
=> :penguin: Add systemd-resolved to Debian images

images/Dockerfile.opensuse-tumbleweed-arm-rpi
This should fix CI:  https://github.com/kairos-io/kairos/actions/runs/4346604653/jobs/7592922961
=> Add missing repository in tumbleweed

overlay/files/system/oem/05_network.yaml
- First disable NetworkManager and wicked
- Then enable systemd services for network and resolv
- Then remove and link /etc/resolv.conf
This fixes a case in which systemd-networkd could be enabled before wicked is disabled and because network is linked to wicked it would fail to enable systemd-networkd properly during initramfs.
Also adds a check before removing the resolv.conf, to skip it if it doesnt exist.
Found by immucore running the initramfs as it spits out the errors into the log and we can see them more easily
Fixes #
=> :bug: Improve network stage

go.mod, go.sum, sdk/mounts/system.go, sdk/state/state.go
Newer ghw changes the labels to make it clearer which is which, as you can have a filesystem label AND a device label.
Unfortunately the behaviour changed and the old label has now moved to filesystemlabel so update ghw and fix that.
https://github.com/jaypipes/ghw/pull/316
https://github.com/jaypipes/ghw#block-storage
```
ghw.Partition.Label contains the label for the partition itself. On Linux systems, this is derived from the ID_PART_ENTRY_NAME udev entry for the partition.
ghw.Partition.FilesystemLabel contains the label for the filesystem housed on the partition. On Linux systems, this is derived from the ID_FS_NAME udev entry for the partition.
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
=> Bump ghw and fix state

.github/workflows/release.yaml
Now framework tags contains the flavor
so we build Image `quay.io/kairos/framework:v2.0.0-alpha1_ubuntu-22-lts` and need to use the same name for the signing
Fixes #
=> :robot: Push proper framework tag

.github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml
This seems to be much more stable as we use loopback mounts, and those could be used by the system already. Running earthly inside its own container fixes this
=> :robot: Use earhly script for ARM builds

.github/workflows/image-arm.yaml, images/Dockerfile.alpine-arm-rpi
Dependencies make the image size grow as such it needs changes in the layout - this is not an issue by itself if not that it would cause to exceed our current 16GB size requirements.
Fixes #1118 
Supersedes #1123
=> :penguin: Drop zfs from alpine-arm images

CONTRIBUTING.md
Document some guiding principles for the scope and ideals of the Kairos project for the purposes of shaping and organizing contributions.
The project backlog is now sprawling, such that it is difficult to readily tell what issues should be prioritized. This is an attempt to define values for the project that can help give structure to the planning of efforts and to help contributors have an intuition for what fits into the scope of the project.
The very concept of the list is a proposal, as well as the particular list. I recommend, though, not seeing the list as something... immutable.
=> :book: "Guiding user stories" in contributor guidelines

images/Dockerfile.opensuse-leap
The `which` package was listed twice in the `zypper install` command. One time should be enough.
=> :seedling: remove duplicate installation of `which` package in opensuse-leap Dockerfile

docs/content/en/docs/Architecture/meta.md, docs/content/en/docs/Reference/cli.md, docs/content/en/docs/Reference/recovery_mode.md, docs/content/en/docs/Reference/troubleshooting.md, docs/content/en/docs/Upgrade/kubernetes.md, tests/assets/autoinstall.yaml
=> :book: Add documentation on how to gate upgrades with kyverno

docs/content/en/docs/Development/debugging-station.md
This adds notes on how to use entanglement and edgevpn to create debugging stations for development
cc @jimmykarily
=> :book: Add development notes for debugging stations

.github/run_test.sh, .github/workflows/image.yaml, framework-profile.yaml, go.sum
Includes new packages for immucore and grub2 livecd Removes install_test script, just run ginkgo directly
Fixes #1116
=> :arrow_up: Bump repositories

Earthfile, internal/agent/validate.go, internal/agent/validate_test.go
Validator was mistakenly identifying a long yaml as a file and trying to open it, which failed with an error of filename too long.
This was not catched in order to identify that the source is not a file but a yaml, so it was directly returning the error.
This patch adds that error to the list in order ot identify the source to validate as yaml. Also adds a couple of tests for this functionality.
Fixes #994
=> :bug: Fix validator on long strings

.github/workflows/image-arm.yaml, .github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml
Attempt to fix: #1228 and #1055
I don't really like this bashism, but there seems to be no better way at the moment. Cosign attach sbom generates a new image - and the only way to get it's digest is parsing cosign output :shrug: 
Open to other solutions, but so far didn't had luck with other approaches, this is the output of `cosign attach sbom`:
```
WARNING: Attaching SBOMs this way does not sign them. If you want to sign them, use 'cosign attest --predicate core-alpine-arm-rpi-v2.0.0-alpha3-sbom.spdx.json --key <key path>' or 'cosign s
ign --key <key path> --attachment sbom <image uri>'.                                                                                                                                          
Uploading SBOM file for [quay.io/mudler/tests:sbom] to …
```
=> :robot: Attach and sign SBOM

.github/workflows/release.yaml
**What this PR does / why we need it**: We were not using self-hosted runners to build framework images during release
Fixes #1240
=> :robot: Build framework images on self-hosted during release

.github/workflows/release.yaml
Fixes #1240 
Seems we already push with docker in the step right afterwards
=> :robot: Disable push from Earthly for framework images

docs/content/en/docs/Advanced/coco.md
=> Add instructions on how to use the `coco` bundle

docs/netlify.toml
Docsy comes with the /docs/community-guidlines/ url as part of the theme. I thought it would be much easier just to add a redirect in netlify than re-define the whole layout
Fixes #1301
=> :bug: Add a netlify redirect for /docs/contribution-guidlines/

pkg/config/collector/collector.go, pkg/config/collector/collector_test.go
=> :bug: Fix agent not able to get subkeys

Earthfile
Looks like I added the skip to the rpi images but those have dracut and we should use that to generate the initrd and link it
Fixes #1300
=> :bug: Fix rpi initrd not being linked

internal/agent/reset.go
=> :bug: Ensure data source is ready during reset

.github/cypress_tests.sh, .github/workflows/webui.yaml, .gitignore, Earthfile, internal/webui/public/cypress.config.js, internal/webui/public/cypress/e2e/spec.cy.js, internal/webui/public/index.html, internal/webui/public/package-lock.json, internal/webui/public/package.json
This adds basic webUI tests to our workflows based of cypress.
Currently the deployment and test is simplified, as it runs a local webui agent inside earthly and tests several parts on the UI and some of the functionality (validation)
Hopefully in the near future this is expanded to use a full qemu VM with the webui running and we can trigger the full install from there although its  a bit nastey as it would be earthly -> ginkgo -> qemu -> cypress
Fixes #
=> Add cypress tests for web UI

pkg/github/releases_test.go
Looks like we only get a small subset of the releases so we cant check for a specific number in the list that we get
Fixes #
=> :robot: Fix release tests

cmd/agent/main.go, internal/agent/upgrade.go, pkg/github/releases.go, pkg/github/releases_test.go
By default get 30 releases and skip any pre-releases found. Allow toggling showing pre-releases both for upgrade and for listing them
Fixes #
=> :sparkles: Allow showing pre-releases on upgrade options

.github/workflows/image.yaml
As we now have also arm generic images, the download-latest job is now downsloading both isos as they match in name.
Adds a tighter regex to download the proper images
Fixes #
=> :robot: Download only the x86 iso for testing

framework-profile.yaml, images/Dockerfile.fedora, images/Dockerfile.rockylinux
immucore v0.17.0 now needs the lvm module in the initramfs, so all distros need it installed so it can inject it
Fixes #1330
=> :bug: Add missing lvm packages in fedora+rockylinux

Earthfile
Enables LVM  by default on RPI images, which means that the recovery partition will be an lvm partition
Fixes #1271
=> :sparkles: Set rpi images with lvm by default

.github/workflows/image.yaml, .github/workflows/release.yaml
Currently no self-hosted machines available
Fixes #
=> :robot: Run jobs on ubuntu-latest instead of self-hosted

overlay/files/system/oem/00_rootfs.yaml
Looks like we were doing it on the same stage which made no sense as by that time there may not be a machine-id yet.
Now the machine id is splitted in two. If we have a stored machine ID, during initramfs we copy it over /etc so systemd doesnt recreate one and during fs if we dont have a stored machien id, we save the one generated.
This results in the machine-id being persistent across reboots and as a side effect things like getting the same dhcp ip on reboot now works out of the box.
Fixes #1381
=> :bug: Fix persistent machine-id

images/Dockerfile.fedora
Bumps fedora from 36 to 38 and uses the latest tag so we don't have to be updating it every time there's a new release
Fixes #1431
=> :penguin: Use latest for fedora images

.github/flavors-arm.json, .github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml, Earthfile, framework-profile.yaml, images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson, images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin, overlay/files-nvidia/etc/cos/bootargs.cfg, overlay/files-nvidia/etc/dracut.conf.d/iscsi.conf
**What this PR does / why we need it**: Adds initial support for Nvidia AGX Orin. Will follow up and iterate with the image hooked from the CI.
The difference with the other flavors is that instead of a flashable SD image, we prepare the partitions .img files that are ready to be flashed to the eeprom, and we just pack that as part of the releases so others don't have to re-create those images again.
Next:
- Try upgrades
- Create equivalent image in provider-kairos
- Add documentation on how to flash the board with the image files
- See what we can do about resets https://github.com/kairos-io/kairos/issues/622 
Related to #1395
=> :penguin: Add Jetson agx orin image

.github/workflows/release.yaml, Earthfile, UKI-experimental.md, UKI-hack.md, overlay/files/system/oem/00_rootfs.yaml, overlay/files/system/oem/10_accounting.yaml, overlay/files/system/oem/11_persistency.yaml
=> Build and publish UKI images in our pipeline

Earthfile, overlay/files-rpi/etc/cos/bootargs.cfg, overlay/files/etc/modprobe.d/vc4-blacklist.conf
=> Revert ":sparkles: Directly blacklist the vc4 module everywhere"

.github/workflows/image.yaml
framework is built as part of the iso build and we only need to push them on master and release so they can be consumed, we dont want to keep pushing them on each PR
Fixes #
=> :robot: Drop framework building from PR builds

images/Dockerfile.debian, images/Dockerfile.rockylinux, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-20-lts-arm-rpi, images/Dockerfile.ubuntu-22-lts, images/Dockerfile.ubuntu-22-lts-arm-rpi, images/Dockerfile.ubuntu-arm-rpi
Should be not needed as immucore is mounting the tmp dir and systemd will make sure the mount is on once switched to the new root after initramfs
Fixes #
=> :seedling: Drop tmp.mount services

overlay/files/system/oem/00_rootfs.yaml
initramfs stage runs under a chroot.
If we do the mount in initramfs we are troublemaking the chroot mounts that the stage uses to run the config files. Nothing should be mounted in the binded paths during that stage to avoid issues as after the stage is finished, the chroot is removed fully, so those mounts would get lost.
Fixes k3s issues on provider-kairos
Fixes cgroups for alpine
=> :bug: Alpine: Mount bpf system once we boot

.github/workflows/image-arm.yaml, Earthfile
Should fix the broken rpi images in which several hundreds Mb are missing due to closing the loop devices too fast and too aggresive
Fixes #
=> :arrow_up: Bump osbuilder

images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts, images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin, images/Dockerfile.ubuntu-20-lts-arm-rpi, images/Dockerfile.ubuntu-22-lts, images/Dockerfile.ubuntu-22-lts-arm-rpi, images/Dockerfile.ubuntu-arm-rpi
We do remove it in case it is present in the base image already, but there is no reason to install it in the first place if isn't there.
=> :penguin: do not install unattended upgrades

.github/workflows/release.yaml
regex was missing the asterisk so it didnt find any artifacts for the release
Fixes #
=> :robot: Fix uki release artifacts

Earthfile
With the change on the golang image to the newest debian release, the metapackage qemu is no longer available.
This patch drops it as we explicitely install the qemu packages and we need no metapackages
Fixes #
=> :robot: Fix golang image not having qemu packages anymore

overlay/files/system/oem/10_accounting.yaml, tests/upgrade_latest_cli_test.go
Currently is only possible to get the boot process via the serial output wiht no login available.
This patch enables login via the serial console under openrc systems
Fixes #
=> :sparkles: Allow serial login in openrc systems

overlay/files/system/oem/00_rootfs.yaml
Immucore is already mounting /tmp on boot so we should not re-mount it, or at least if we do, we should check first if its mounted to not shadow existing /tmp files
Fixes #1526
=> :bug: Do not remount /tmp under alpine

.github/flavors.json, .github/workflows/image.yaml, .github/workflows/release.yaml, framework-profile.yaml, tests/upgrade_cli_test.go
to allow users to build fips enabled ubuntu flavors from scratch
https://kairos.io/docs/reference/build-from-scratch/
Fixes https://github.com/kairos-io/kairos/issues/1539
=> Build ubuntu fips framework image

images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin
Those packages are present in a standard installation
Fixes #
=> :penguin: add nvidia packages to orin image

.github/workflows/image.yaml, Earthfile
Master is currently broken not because the test is failing but because the test image was done 12 hours ago. I think it's common that we merge something at night so it would be nice to have those images at least 24 hrs instead of just 8
=> :robot: Increase test images livespan to 24h

Earthfile, images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin, overlay/files-nvidia/etc/elemental/config.yaml, overlay/files-nvidia/system/oem/mount.yaml
Note: ~~requires docs updates as the partition XML file changed too~~ docs pr: https://github.com/kairos-io/kairos-docs/pull/43
This PR does the following:
- Add cublas and opencv (so can test the GPU from the image)
- Bump the default image size to allow more space for packages
- Adds a workaround for `/usr/local`. The Orin images currently are installing files into `/usr/local`, and as such are not visible on boot (`/usr/local` is mounted to `COS_PERSISTENT`). Introduce here a cloud-config that attempts to overlay the content of the image to `/usr/local` during boot. The consequence is that there will be a folder inside the partition `local` and one `work` due to how the nature of overlayfs works.
=> :bug: Orin fixups

examples/byoi/ubuntu-fips/Dockerfile, examples/byoi/ubuntu-fips/README.md, examples/byoi/ubuntu-fips/build.sh, examples/byoi/ubuntu-fips/dracut-broken-iscsi-ubuntu-20.patch, examples/byoi/ubuntu-fips/dracut.conf, examples/byoi/ubuntu-fips/pro-attach-config.yaml, examples/byoi/ubuntu-fips/run.sh
It adds a full e2e example to build a custom ubuntu fips-enabled image (license subscription is needed)
=> :book: Add example to build an image from scratch for ubuntu fips

.github/flavors.json, examples/byoi/fedora-fips/Dockerfile, examples/byoi/fedora-fips/README.md, examples/byoi/fedora-fips/build.sh, examples/byoi/fedora-fips/dracut.conf, examples/byoi/fedora-fips/run.sh, examples/byoi/rockylinux-fips/Dockerfile, examples/byoi/rockylinux-fips/README.md, examples/byoi/rockylinux-fips/build.sh, examples/byoi/rockylinux-fips/dracut.conf, examples/byoi/rockylinux-fips/run.sh, examples/byoi/ubuntu-fips/Dockerfile, framework-profile.yaml
Fixes #362 
Adds fips e2e example for:
- fedora
- rockylinux
~Draft as needs to validate with the latest images~
Renames also the `ubuntu-20-lts-fips` framework image to `fips-systemd` as works as well for rocky and fedora.
=> :book: Add byoi fedora/rockylinux-fips example

.github/workflows/image.yaml, tests/tests_suite_test.go, tests/uki_test.go
Signed-off-by: Itxaka <itxaka.garcia@spectrocloud.com>
Fixes #
=> 🤖 Add simple UKI test

tests/uki_test.go
So we dont start the vm without the required env vars
Brought up by @jimmykarily 
To not waste CI cycles
Fixes #
=> :robot: Add guards to UKI test

overlay/files/etc/systemd/system/kairos-webui.service, overlay/files/etc/systemd/system/kairos.service
Marks the services of kairos and webui with a max stop time of 10 seconds to not block when shutting down or restarting as they get the default 1m30s and that slows the whole system.
10s should be more than enough for the services to stop.
Fixes #
=> :bug: Stop kairos services in proper time

.github/workflows/image-arm-pr.yaml, .github/workflows/image-arm.yaml, .github/workflows/image-pr.yaml, .github/workflows/image.yaml, .github/workflows/reusable-encryption-test.yaml, .github/workflows/reusable-install-test.yaml, .github/workflows/reusable-qemu-acceptance-test.yaml, .github/workflows/reusable-qemu-bundles-test.yaml, .github/workflows/reusable-qemu-reset-test.yaml, .github/workflows/reusable-upgrade-with-cli-test.yaml, .github/workflows/reusable-zfs-test.yaml, Earthfile
Relates to #1109
Running `earthly +all` produces the following artifacts:
```
kairos-core-opensuse-leap-amd64-generic-v2.3.0-11-gc84e074-dirty-grype.json
kairos-core-opensuse-leap-amd64-generic-v2.3.0-11-gc84e074-dirty-grype.sarif
kairos-core-opensuse-leap-amd64-generic-v2.3.0-11-gc84e074-dirty-initrd
kairos-core-opensuse-leap-amd64-generic-v2.3.0-11-gc84e074-dirty.ipxe
kairos-core-opensuse-leap-amd64-generic-v2.3.0-11-gc84e074-dirty-ipxe.iso.ipxe
kairos-core-opensuse-leap-amd64-generic-v2.3.0-11-gc84e074-dirty-ipxe-usb.img.ipxe
kairos-core-opensuse-leap-amd64-generic-v2.3.0-11-gc84e074-dirty.iso …
```
=> ✨ Introduce new naming convention for artifacts

images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin
Seems that apt-get pulls down the apt source repository, but that is wrong as it does not contains the board:
```
cat nvidia-l4t-apt-source.list 
#
deb https://repo.download.nvidia.com/jetson/common r35.3 main
deb https://repo.download.nvidia.com/jetson/<SOC> r35.3 main
```
While our definitions are in: `/etc/apt/sources.list`
=> :bug: duplicate repository definition

.github/workflows/image.yaml
=> :robot: Use proper job for the matrix get in framework

.earthlyignore, Earthfile, tests/assets/raw_image.yaml
Useful to emulate what osbuilder does to build cloud images for local testing
Fixes #
=> :robot: Add raw image target to earthly

overlay/files/system/oem/00_rootfs.yaml
Seems an important dir to have it persistent, plus containerd snapshot will not work on an overlay system
Fixes #
=> :seedling: Add /var/lib/containerd to bind paths

.github/workflows/image-arm.yaml
Master ARM pipeline is currently failing with
```
Invalid workflow file: .github/workflows/image-arm.yaml#L90
The workflow is not valid. .github/workflows/image-arm.yaml (Line: 90, Col: 9): Job 'notify' depends on unknown job 'docker'.
```
see https://github.com/kairos-io/kairos/actions/runs/5819487177
this is because the name was changed during the refactoring
=> Fix arm pipeline dependency

.github/workflows/bump_repos.yml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml, .gitignore, Earthfile
Use the new luet 0.35 which provides a way of storing the installed artifacts in the system to bundle the versions file with the framework files so we always have a reference for what was installed in the framework and what versions.
Also reworks the CI pipeline for the bump repos to provide a diff of changes to **installed** packages, not to the full repo unfortunately, as part of the PR creation so its easily visible what changed that directly affects kairos
Also during iso building, extract and upload the versions to the artifacts so its easier to check what packages were installed in a given iso during CI.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …
=> Bundle luet versions in the framework

tests/assets/suc.yaml, tests/provider_upgrade_k8s_test.go, tests/provider_upgrade_latest_k8s_test.go
because it was returning success too early since the checks were too loose or even wrong.
E.g. we didn't even wait for the Pods to be ready (wrong test condition) and we only tested that there is a "v" in the version which was true even before the upgrade.
Fixes #
=> Fix test that wasn't testing anything

Earthfile, framework-profile.yaml, images/Dockerfile.almalinux, images/Dockerfile.alpine, images/Dockerfile.debian, images/Dockerfile.fedora, images/Dockerfile.opensuse-leap, images/Dockerfile.opensuse-tumbleweed, images/Dockerfile.rockylinux, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin, images/alpine/bootargs.cfg, images/debian/bootargs.cfg, images/nvidia/bootargs.cfg, images/opensuse/bootargs.cfg, images/redhat/bootargs.cfg, images/rpi/bootargs.cfg
because we need them before any stages are run (grub needs them)
Related PR that removes them from the luet package: https://github.com/kairos-io/packages/pull/391
=> Bring back the bootargs.cfg files to the base image

images/Dockerfile.alpine, images/Dockerfile.debian, images/Dockerfile.opensuse-leap, images/Dockerfile.opensuse-tumbleweed, images/Dockerfile.ubuntu, images/rpi/bootargs.cfg, images/rpi/config.txt
Fixes the serial output on rpi4. We also need to check if this works on rpi3 otherwise we have to apply this only on rpi4.
Also this fix is an explicit fix  for the `mini-uart's driver (8250)`. I'm not sure if there are other versions of that driver out there that need a similar option in the cmdline
=> Fix rpi4 serial

.github/workflows/release-arm.yaml
relates to #1766 
From the generic, there are files that don't need to be uploaded, with this change we only upload iso and sha
From the other models, we group all json files into a single scan-reports.tar.gz so we make a few calls less per flavor/version
=> Reduce calls to release API

.github/workflows/release-arm.yaml, .github/workflows/release.yaml
relates to #1766
- reduces some of the calls on the amd release uploads
- fixes the issue with bad substitution from the previous PR
- removes files which should not be uploaded: VERSION, IMAGE and versions.yaml
=> Fix some release API issues

.github/workflows/reusable-qemu-acceptance-test.yaml, .github/workflows/reusable-qemu-reset-test.yaml, Earthfile
- adds a golang-testing image which is cached for the golang version. No need to re-build on every test saving some time
- Reduce external call to generate datasource-iso, since the test call already does it internally and the artifact is not being used anywhere else 
relates to #1708
=> :sparkles: Cache testing image and simplify scripts

.github/flavors-arm.json, .github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-framework-flavor.yaml, .github/workflows/reusable-build-provider.yaml, .github/workflows/reusable-docker-arm-build.yaml, .github/workflows/reusable-image-and-iso-arm-generic.yaml, .github/workflows/reusable-provider-tests.yaml, .github/workflows/reusable-provider-upgrade-latest-test.yaml, .github/workflows/reusable-qemu-acceptance-test.yaml, .github/workflows/reusable-qemu-bundles-test.yaml, .github/workflows/reusable-qemu-netboot-test.yaml, .github/workflows/reusable-qemu-reset-test.yaml, .github/workflows/reusable-upgrade-latest-test.yaml, .github/workflows/reusable-upgrade-with-cli-test.yaml, .github/workflows/reusable-zfs-test.yaml
because our paid runners stopped working. This is a temporary fix until we find the problem.
=> Switch to self-hosted runner

Earthfile, images/Dockerfile.ubuntu
Adds a flag `HWE` to build ubuntu without HWE kernles. It can be used as follows
```
earthly +all --FLAVOR=ubuntu-20-lts --HWE=-non-hwe
```
if you want the HWE kernel you don't need to pass it
It only works for LTS versions
Fixes #1779
=> Easy option to build non-hwe kernels

.github/workflows/reusable-zfs-test.yaml, Earthfile, tests/reset_test.go
Makes the zfs job reuse the download iso to reduce the time it takes for the job.
Merges the 2 reset tests into one as it was creating,installiong and reseting 2 machines in the full test suite but its not needed.
Fixes #
=> Zfs reuse iso

.github/workflows/reusable-upgrade-latest-test.yaml, Earthfile, framework-profile.yaml, images/alpine/bootargs.cfg, images/debian/bootargs.cfg, images/nvidia/bootargs.cfg, images/opensuse/bootargs.cfg, images/redhat/bootargs.cfg, images/rpi/bootargs.cfg
Currently bootargs is not provided with the framework images so its missing a very important piece to boot which results into BYOI being broken.
This patch adds the bootargs.cfg to the framework image. Also the config.txt to the rpi images.
Also drops the kernel/initramfs vars from the bootargs as they are set to the default now in the package.
Also moves the luet clean under the package list generation as it requires the database of luet to list the packages.
Fixes #1770 
Requires: https://github.com/kairos-io/packages/pull/408
=> :art: Bundle bootargs with framework images

images/Dockerfile.almalinux, images/Dockerfile.alpine, images/Dockerfile.debian, images/Dockerfile.fedora, images/Dockerfile.opensuse-leap, images/Dockerfile.opensuse-tumbleweed, images/Dockerfile.rockylinux, images/Dockerfile.ubuntu, images/Dockerfile.ubuntu-20-lts-arm-nvidia-jetson-agx-orin
Needed for the last partition automatic expansion, mainly useful for devices like rpi
Fixes #
=> :bug: Add growpart to base images

Earthfile
It was matching before on ubuntu flavours and copying the debian one all the time in rpi stuff
Also adds a check to copy it only if its not there already so we dont touch it on other artifacts
Fixes #
=> :bug: Fix bootargs matcher for rpi

tests/assets/live-overlay.tmpl, tests/bundles_test.go
Part of: https://github.com/kairos-io/kairos/issues/1821
Needs this: https://github.com/kairos-io/packages/pull/437 (merged here: https://github.com/kairos-io/kairos/pull/1822)
TODO: Documentation update. E.g. https://kairos.io/docs/advanced/livelayering/#installing-extensions
=> Change where systemd-sysext extensions are installed

.github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-framework-flavor.yaml, .github/workflows/reusable-build-provider.yaml, .github/workflows/reusable-docker-arm-build.yaml, .github/workflows/reusable-image-and-iso-arm-generic.yaml, .github/workflows/reusable-provider-tests.yaml, .github/workflows/reusable-provider-upgrade-latest-test.yaml, .github/workflows/reusable-qemu-acceptance-test.yaml, .github/workflows/reusable-qemu-bundles-test.yaml, .github/workflows/reusable-qemu-netboot-test.yaml, .github/workflows/reusable-qemu-reset-test.yaml, .github/workflows/reusable-upgrade-latest-test.yaml, .github/workflows/reusable-upgrade-with-cli-test.yaml, .github/workflows/reusable-zfs-test.yaml
=> Use the upstream luet-install-action again

Earthfile
It now should use the generic bootargs like the rest of the flavors
Fixes #
=> :robot: Fix systemd-fips framework trying to copy non-existing file

Earthfile
Useful for testing to have the artifacts directly
Fixes #
=> :robot: Add target to save local uki artifacts

Earthfile, framework-profile.yaml
bootargs.cfg for grub and config.txt for rpi are now provided via luet packages
Fixes #
=> :art: Provide bootargs via package

images/Dockerfile.almalinux, images/Dockerfile.rockylinux, images/Dockerfile.ubuntu
Some utils were missing ffrom initramfs which could lead to issues when running the stages
Fixes #
=> :bug: Add missing deps for initramfs

Earthfile, framework-profile.yaml, images/Dockerfile.alpine
Instead of using a pre-packaged one we can just build it during image build like we do on dracut systems
Fixes #
=> :art: Build alpine initrd during image building

images/Dockerfile.ubuntu
The issue was that both 20 and 22 non-hwe were depending on 22 as their base stage. This change does a rename so I can introduce a common stage for both non-hwe.
=> :bug: Fix Dockerfile for ubuntu 20 lts non-hwe

images/Dockerfile.ubuntu
master is currently broken because I applied this fix only to Ubuntu amd64 :facepalm:
=> :robot: Apply base image fixes to arm

.github/workflows/image-pr.yaml, .github/workflows/image.yaml, Earthfile, naming.sh
several fixes to CI, one for os-release
Signed-off-by: Itxaka <itxaka@kairos.io>
Fixes #1960
Fixes #1959
Fixes #1954
=> 🤖 Run bundles test on tumbleweed

.github/flavors.json
Now that we have the families to build, we can kinda trust that maintaining the rocky flavor will automatically give us alma.
Would be great if we can build everything all the time but it's expensive and I don't see any users relying on Alma, plus they can still build on their own with our recipe
=> Remove AlmaLinux from building

.github/workflows/image.yaml, tests/provider_decentralized_test.go, tests/provider_upgrade_k8s_test.go
- disable version list test until we have a release with the new repos
- agent no longer tails the provider logs, thats the provider task so check for the start logs in the provider log directly
Fixes #
=> :robot: Fix provider tests

Earthfile
so that KAIROS_ARTIFACT is set. Works with:
https://github.com/kairos-io/packages/pull/535
TODO: Bump the overlay files package when it's built
Fixes #
=> Pass ARTIFACT down to os-release template

framework-profile.yaml, tests/bundles_test.go
fixed here: https://github.com/kairos-io/kairos-sdk/pull/58
This commit makes sure we test this for regressions and pulls the fix in.
Fixes #2019
=> Check for duplicate entries in generated Kairos config

.github/workflows/image.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-framework.yaml, Earthfile
currently we only release amd64 framework images. Making them multi arch allows us to take advantage of the pre-built frameworks in arm. this will be particularly useful for the extraction of the earthly logic into dockerfiles related to #1897
=> Build and release multi arch framework images

Earthfile
So it has the proper grub packages which do not error out on memory
Fixes #
=> :arrow_up: Bump osbuilder tools

tests/provider_upgrade_latest_k8s_test.go
It's failing consistently on master to ping the machine, this gives a bit of extra wait time
=> Wait a bit more for standard upgrade before failing

Earthfile, images/Dockerfile.kairos
:warning: also required before cutting out the final release
This is a revert to something similar to what we were doing before. Ideally, this should not have to happen on the Earthfile but could be done in the Dockerfile. The main issue is that the KAIROS_VERSION, gets appended to the K3S_VERSION within the +version target (plus removing of the internal build number and hardcoding the k3s build number). The real solution to this would be to address https://github.com/kairos-io/kairos/issues/2058 as @jimmykarily pointed out.
=> Fix missing hardcoded k3s build

.github/workflows/image-pr.yaml
I recently had a PR which was green but when merged to master, the standard images started breaking. This adds at least a build of a standard image to avoid such scenarios
=> Add a standard build to PRs

Earthfile
prepare image is only used when building the nvidia, so I don't think we need to have the control flow check. This also simplifies the check for the arm-image which applies to the other boards by removing the nvidia check
=> No need to evaluate sizes for nvidia img build

.github/workflows/image-pr.yaml, .github/workflows/reusable-upgrade-latest-test.yaml
This is necessary to have tests which depend on the latest release, e.g. Ubuntu 23.04, and want to upgrade to the latest build, e.g. Ubuntu 23.10
=> Introduce release_matcher to overwrite flavor release

.github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-base-image.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml, .github/workflows/reusable-docker-arm-build.yaml, .github/workflows/reusable-encryption-test.yaml, .github/workflows/reusable-qemu-acceptance-test.yaml, .github/workflows/reusable-qemu-netboot-test.yaml, .github/workflows/reusable-upgrade-latest-test.yaml, .github/workflows/reusable-upgrade-with-cli-test.yaml
removes VERSION file so it doesn't get released because it causes jobs to step on each others toes
remove more packages from worker
I wanted to use a reusable job for the releasing so we only have to change in one place but it was failing, so I'll open a ticket for that
=> fix pipeline issues during release of v2.5.0

.github/workflows/image-pr.yaml, .github/workflows/reusable-encryption-test.yaml, .github/workflows/reusable-install-test.yaml, .github/workflows/reusable-provider-tests.yaml, .github/workflows/reusable-qemu-acceptance-test.yaml, .github/workflows/reusable-qemu-bundles-test.yaml, .github/workflows/reusable-qemu-reset-test.yaml, .github/workflows/reusable-upgrade-with-cli-test.yaml, .github/workflows/reusable-zfs-test.yaml, Earthfile, tests/provider_upgrade_test.go
This test breaks when `master` branches matches the latest release exactly. That's because the previous version of the command, didn't find any newer releases, thus it didn't return any.
We introduced the `--all` flag to kairos-agent and now the test can get away with it by just listing all releases, older or newer (it doesn't return the current one for obvious reasons).
=> Make sure test doesn't break when master matches the latest release

.github/workflows/uki.yaml, tests/uki_test.go
Now that uki installs follow the normal install path we need to ensure we have a datasource like normal install tests
Fixes #
=> :wrench: Adapt uki test

.github/workflows/image-pr.yaml, .github/workflows/image.yaml, .github/workflows/reusable-install-test.yaml, Earthfile, images/Dockerfile.debian, images/Dockerfile.kairos-debian, images/Dockerfile.kairos-opensuse, images/Dockerfile.kairos-ubuntu, images/Dockerfile.opensuse, images/Dockerfile.ubuntu, tests/install_test.go, tests/tests_suite_test.go
This PR brings new deps, bumps builders and agent to bring secureboot in all flavors but alpine (more ont hat below)
Currently to enable secureboot in a given X flavor we need to make sure to use the artifacts from that falvor specifically as they are all signed with the distro owner key, so the chain of validation works as expected.
shim (dual signed Microsoft and distro owner) -> grub (distro owner signed) -> kernel (distro owner signed)
So unless there comes a time where the shim is signed by Microsoft and ALL the distro owners (so you can chainload all grubs and kernel signed by all of them) we need to specifically use the distro artifacts so the signatures match.
This PR brings a new enki version(inside osbuilder) which builds the iso using the specifci distro artifacts (instead of …
=> :sparkles: Enable secureboot for all flavors (minus alpine)

images/Dockerfile.kairos-rhel, images/Dockerfile.rhel
Probably missed when refactoring to install different pacakges depending on whether the base image is using epel or fedora base
=> Remove duplicated zfs installation on rhel

.github/workflows/release.yaml, .github/workflows/uki.yaml, Earthfile
This new target requires to pass an existing kairos image, which means it's a two step proces e.g.
```
earthly --push +base-image --....
earhtly +uki-enki --BASE_IMAGE=<pushed-image-from-previous-step>
```
I first tried to have it in a single step but I'm not sure if it's possible since enki cannot access the local registry from Earthly. Even when using `WITH DOCKER` this is problematic because our uki building image is on fedora. We have to use fedora because Ubuntu does not have the latest packages e.g. ukify. However, Earthly complains that it doesn't know the distro, so considers it's a Debian and then proceeds unsuccessfully to try to install packages via `apt`.
Please let me know if I'm missing something here. And if it's not possible, then the question for me is really, about why …
=> Add target to transform kairos image into UKI

.github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml
on master we don't want to push all the sbom files since the tag is always the same and we don't go back to clean the old sbom files
=> Do not push sbom master files to repo

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
Since ubuntu 23.10 firmware files now come pre-compressed in the packages so we would recompress them again. Fix the find to not take into account already compressed files
Fixes #2236
=> :bug: Do not recompress compressed firmware

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
```
all *failed* |   2 files compressed : 46.04% (   808   B =>    372   B)
all *failed* | ./cdspr.jsn          : 46.90%   (   403 B =>    189 B, ./cdspr.jsn.zst) 
all *failed* | ./regulatory.db.p7s  : 89.93%   (  1.15 KiB =>   1.04 KiB, ./regulatory.db.p7s.zst) 
all *failed* | ./regulatory.db      : 43.57%   (  4.39 KiB =>   1.91 KiB, ./regulatory.db.zst) 
all *failed* | 310 files compressed : 25.29% (   908 KiB =>    230 KiB)
all *failed* |  11 files compressed : 21.31% (   474 KiB =>    101 KiB)
all *failed* | ERROR
all *failed* |       The command
all *failed* |           RUN find /usr/lib/firmware -type f ! -name "*.zst" -execdir zstd --rm -9 {} +
all *failed* |       did not complete successfully. Exit code 1
```
https://github.com/kairos-io/kairos/actions/runs/7843857719/job/2140508 …
=> Run zst per file

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
I was testing Ubuntu 24.04, and it works with amd64. It will need proper testing and also to add it to flavors.json. Adding that to the main ticket
relates to #2138
=> Ubuntu 24.04 arm64 generic

.gitignore, Earthfile, images/Dockerfile.kairos, images/Dockerfile.ubuntu
In this PR:
- remove some packages
- zfs: if we remove then there's no issue with nohang any more, but then we probably want to get rid of the test too? WDYT? https://github.com/kairos-io/kairos/issues/2195
- introduce the concept of having an image be built for UKI, this image will not install dracut and will not create an initramfs, it will also not include GRUB (see grub and systemd-boot targets)
Relates to #2283
=> Slim down Ubuntu

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
When doing the changes for space in UKI, I made a note to fix this for 22.04 but didn't think that I would also need to fix it for arm
=> Add dracut-live to Ubuntu arm64 22+

.github/workflows/image.yaml
Currently, we don't build Ubuntu standard on master, we do have one on PR, but I think it's worth adding here since it's such a crucial flavor. Also, this avoids that in order to see the issues we have to re-run the release pipeline but can be caught on master.
=> Add Ubuntu standard build on master

Earthfile
As we now dont need the IMAGE var to extract the iso, there is no point in having to pull the full BASE_IMAGE just to extrac the name.
This should speed up the uki iso generation
=> :robot: Do not double pull the BASE_IMAGE on uki iso

.github/workflows/image-pr.yaml, .github/workflows/image.yaml
This is because zfs is not being installed on 23+ since it clashes
with nohang and it's not a requirement to have
=> Use Ubuntu 22 LTS for ZFS test

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
nohang apt repo is not actively maintained, install it from source instead.
Fixes #2195
=> Install nohang from source for ubuntu

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
=> Move nfs-common to common build target in ubuntu flavor

images/Dockerfile.nvidia
Even if nohang is a welcome addition, first it's better to not use testing repo - second nohang is optional as it is not really a requirement for things to be functional
#2428
=> fix(nvidia): do not ship nohang in nvidia-arm builds

images/Dockerfile.kairos, images/Dockerfile.kairos-alpine, images/Dockerfile.kairos-debian, images/Dockerfile.kairos-opensuse, images/Dockerfile.kairos-rhel, images/Dockerfile.kairos-ubuntu
The jetson produces `/boot/Image` which wasn't caught by the previous mechanism
fixes #2461
=> Symlink any /boot/Image* to /boot/vmlinuz

.github/flavors.json, .github/workflows/image-pr.yaml, .github/workflows/image.yaml, .github/workflows/release.yaml, .github/workflows/reusable-uki-test.yaml, .github/workflows/uki.yaml, .github/workflows/uki_branches.yaml, images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
And introduce reusable test for uki
relates to #2138
=> Add Ubuntu 24.04 to pipelines

images/Dockerfile.nvidia
**What this PR does / why we need it**: https://github.com/kairos-io/kairos/issues/2467
=> fix(orin): disable ISCSI in the initramfs generation

README.md
https://github.com/kairos-io/kairos/issues/2493
=> readme: add links to project governance

images/Dockerfile.kairos-opensuse, images/Dockerfile.opensuse
relates to issue #1538 and pr #2340
Fixes #
=> :bug: Move nfs-utils to common build target in opensuse flavor

.github/workflows/image.yaml, .github/workflows/release.yaml, .github/workflows/uki.yaml, .github/workflows/uki_branches.yaml
It's still part of the flavors.json until we are sure we don't need to build more 23.10 images
relates to https://github.com/kairos-io/kairos/issues/2481
=> Remove 23.10 from the test pipelines

.github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml, .github/workflows/reusable-docker-arm-build.yaml, .github/workflows/reusable-encryption-test.yaml, .github/workflows/reusable-qemu-acceptance-test.yaml, .github/workflows/reusable-qemu-netboot-test.yaml, .github/workflows/reusable-upgrade-latest-test.yaml, .github/workflows/reusable-upgrade-with-cli-test.yaml, .github/workflows/uki.yaml, Earthfile
I hope this fixes the issue with the building of ubuntu 22 arm, if it works then it will also need to be merged on master but I think some workflows changed a bit so might be easier to just do in a different commit than to cherry pick
```
2024-05-14T23:20:31.4790490Z 208517     gcc-13
2024-05-14T23:20:31.4791190Z 193002     g++-13
2024-05-14T23:20:31.4791701Z 181224     cpp-13
2024-05-14T23:20:31.4792392Z 123578     linux-modules-6.5.0-1018-azure
2024-05-14T23:20:31.4792842Z 115583     containerd.io
2024-05-14T23:20:31.4793143Z 98484      snapd
2024-05-14T23:20:31.4793569Z 94367      docker-ce
2024-05-14T23:20:31.4793972Z 81895      linux-azure-6.5-headers-6.5.0-1018
2024-05-14T23:20:31.4794409Z 70069      gcc-12
2024-05-14T23:20:31.4794811Z 52747      gcc-11
2024-05-14T23:20:31.4795099Z …
```
=> Add more space on v3.0 releases

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
Not sure if this is the right approach but since it's quite simple to test this with the multi stage dockerfile then I wanted to give it a go
Not an original idea, recommended by Kevin
relates to https://github.com/kairos-io/kairos/issues/2565
=> Install limited amount of modules for UKI Ubuntu

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
This brings the systemd-dissect tool which is needed to analyze sysext images and check if they are signed and pass validation
Should add about 1 Mb and it has no deps
Fixes #
=> Add systemd-continaers to ubuntu

Earthfile
=> Bump framework to v2.8.5

.github/workflows/reusable-uki-test.yaml
=> Fix dangerous workflow

SECURITY.md
=> Link to GH Security Draft Advisory form

.github/workflows/image.yaml
This one does not run on PRs so I missed it :( there are still others that might break, specially on release since I haven't run those at all
=> Add permissions to reusable-provider-tests

images/Dockerfile.kairos-opensuse, images/Dockerfile.opensuse
Seems like we were only installing cryptsetup in amd64 and immucore dracut install requires cryptsetup. This caused the list of required binaries in the initramfs to fail in the middle and not install the next ones.
So in the case of arm64 (rpi) this mean that binaries were installed up to the cryptsetup, then it failed and didnt continued installing the required binaries, which were the ones being used to expand the partition to max size on boot.
This makes cryptsetup part of the common install for both arches
Fixes #2682
=> :bug: Install cryptsetup for all arches in opensuse

Earthfile
https://github.com/kairos-io/kairos/issues/1792
=> Bump framework to v2.9.2

.github/ISSUE_TEMPLATE/release.md
We've had issues with FS expansion and with cgroups that both break k3s, plus it's the main software to test on a standard image
=> Add k3s test for arm release checklist

images/Dockerfile.kairos-rhel, images/Dockerfile.rhel
```
all | --> RUN systemctl disable dnf-makecache.timer
all | Removed "/etc/systemd/system/timers.target.wants/dnf-makecache.timer".
```
Fixes #2664
=> :penguin: Disable make cache timer on fedora

tests/autoinstall_test.go, tests/install_test.go, tests/uki_test.go
Related to https://github.com/kairos-io/kairos/issues/2773
=> :robot: Check that install/recovery services are off during active boot

images/Dockerfile.kairos, images/Dockerfile.kairos-alpine, images/Dockerfile.kairos-debian, images/Dockerfile.kairos-opensuse, images/Dockerfile.kairos-rhel, images/Dockerfile.kairos-ubuntu
the pcrlock service will generate a policy on boot which when adding our measurements policy, will also be read and clash. You can only either use a pcrlock policy or a measurements policy.
This disables the service until the pcrlock stuff is more stable and we can move to use it directly
Fixes #
=> :penguin: Disable pcrlock for all systemd distros

images/Dockerfile.kairos, images/Dockerfile.kairos-alpine, images/Dockerfile.kairos-debian, images/Dockerfile.kairos-opensuse, images/Dockerfile.kairos-rhel, images/Dockerfile.kairos-ubuntu
We used to rely on a hidden feature of sysinfo that created a filled machine-id during initramfs so systemd did not trigger the first boot service.
Now on the newer agent versions, that hidden functionality has gone away so if we remove it teh file, systemd will think that this is a new system and will do some work behind our back initializing and break things around.
So we need to create en empty machine-id file so systemd knows that we dont want to run the first boot services/target
Fixes https://github.com/kairos-io/kairos/issues/2773
=> :bug: Empty machine-id instead of removing it

Earthfile
Instead of waiting for them to trickled down, we can easily test them and integrate them intot he rootfs.
This provides a OVERLAY_FILES_DEV_BRANCH argument that can be set to a branch or commit of the packages repo in order to test ongoing branches or single commits directly.
Currently does not remove the existing files so anything that removes files cannot be tested by this as we cant now in advance which files to delete, so it only works by overwriting the files or adding new ones.
Fixes #
=> :wrench: Allow testing overlya files branches

Earthfile
This does not work with remote execution today.  For example, if I made a new `Earthfile` in a different repository that contained this:
```yaml
kairos-image:
BUILD github.com/kairos-io/kairos:3.1.1+base-image \
--BASE_IMAGE=ubuntu:24.04 \
--BOOTLOADER=grub \
--FAMILY=ubuntu \
--FLAVOR=ubuntu \
--FLAVOR_RELEASE=24.04 \
--MODEL=generic \
--VARIANT=standard
```
It will fail to build with:
```
g/k/kairos:v3.1.1+base-image | resolve build context for dockerfile: read build file: open images/+kairos-dockerfile/Dockerfile: no such file or directory
Error: async earthfile2llb for github.com/kairos-io/kairos:v3.1.1+base-image: /tmp/earthly-git3649441421/Earthfile:263:4 from dockerfile: resolve build context for dockerfile: read build file: open images/+kairos-dockerfile/Dockerfile: no such file …
```
=> :bug: Fix +base-image for Remote Execution

.github/workflows/release-arm.yaml
so we can release generic artifacts again
=> Add permissions to generic arm release pipeline

examples/cloud-configs/wifi.yaml
YAML structure was missing "files" so wasn't created. PSK must be quoted.
NB: I've not tested this as I don't have a Raspberry Pi to hand, but I have verified the PSK needs to be quoted and the file adding from my other PR to configure WiFi on alpine
=> :bug: Fix wifi cloud-config example

examples/cloud-configs/wifi-alpine.yaml
Adds a sample config for WiFi on alpine. Have noticed only Alpine & RPi openSUSE has wpa_supplicant - will update docs later in a separate PR and reference this config
I've never used connman before, so there could be a better way of doing this!
=> :book: Add alpine wifi cloud-config

tests/provider_decentralized_test.go, tests/provider_upgrade_k8s_test.go, tests/provider_upgrade_latest_k8s_test.go
ShouldNot(Equal(currentVersion), out) is a method call and as such, it received the value of `out` at the time of the call. That was not the updated value after the `Eventually` timeout had passed but rather the value from the previous call that populated it.
This made the test output very confusing because, even though the upgrade Pod was erroring out, the output shows the cluster being only some seconds old and the pod still being created (ouch!)
Fixes #
=> Fix test printing old value for debugging

Earthfile
Allows to set `KAIROS_PROVIDER_DEV_BRANCH` during earthly build to point at a provider branch or commit as part of the base image to test unreleased versions
Fixes #
=> :robot: Allow testing provider dev versions

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
We were going a bit wide and installing everything under tpm2-* This brougth a userspace daemon for tpm2 which was failing to start in non-tpm enabled nodes, thus failing the systemd status and blocking boot
We added a workaround to time out the service but we should directly not have that daemon in there. All our tpm2 stuff uses the in kernel tpm calls as it needs to be really early so the daemon is useless in our workflows.
Fixes #
=> :bug: Do not bindly install all tpm2 tools

.github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml, Earthfile
If we hit a problem with the trivy download, we can make the step that downloads the database a retryable one so we dont stop the actual workflow
Fixes #
=> :Robot: Cache triby DB before running the build

images/Dockerfile.alpine, images/Dockerfile.kairos-alpine, images/Dockerfile.kairos-opensuse, images/Dockerfile.opensuse
because they clash. We keedp haveged only because we can't know if there is special rng hardware or not.
Fixes https://github.com/kairos-io/kairos/issues/2716
=> Don't run both rngd and haveged

.github/workflows/image-pr.yaml, .github/workflows/image.yaml
=> :robot: Add missing secrets: inherit

.github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml, Earthfile
While locally it works as it caches the image witht he DB already on it, on CI it doesnt work and pulls the DB twice, so its the same as it was before.
=> :robot: Revert the trivy DB changes

.github/workflows/image-pr.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml, .github/workflows/reusable-docker-arm-build.yaml, .gitignore, Earthfile
Fixes https://github.com/kairos-io/kairos/issues/2904
Fixes #
=> Cache trivy

.github/workflows/image.yaml
=> Cache trivy in one more pipeline

.github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/reusable-docker-arm-build.yaml
Install arm64 earthly build in arm64 jobs (run under arm64 arch) and removes the uneeded space free step and the qemu install as we dont need any in our workers.
Cancelled all jobs but the arm ones as those are the ones affected by this
=> Install arm64 earthly

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/reusable-uki-test.yaml, Earthfile, images/Dockerfile.kairos, images/Dockerfile.kairos-alpine, images/Dockerfile.kairos-debian, images/Dockerfile.kairos-opensuse, images/Dockerfile.kairos-rhel, images/Dockerfile.kairos-ubuntu, tests/bundles_test.go, tests/provider_decentralized_test.go, tests/tests_suite_test.go, tests/uki_test.go, tests/upgrade_latest_cli_test.go
Otherwise when creating derivatives, the upgrades can overwrite the existing kairos release info adn break the whole thing.
This patch adds the variables into a new /]etc/kairos-release file, as well as keeping them in the usual /etc/os-release file for backwards compatibility
Part of: https://github.com/kairos-io/kairos/issues/2907
=> :bug: Move kairos vars to their own file

.github/workflows/image-arm-pr.yaml, .github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml
because we suspect this is the reason why later jobs that run on those workers don't find the cache.
Might be related to:
https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache
Fixes #
=> Run trivy-cache job on ARM64 worker

.github/flavors.json, .github/workflows/image-pr.yaml, .github/workflows/uki.yaml, images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
24.10 has already been available for a bit, and it would be nice to already include it in our pipeline
This PR also cleans up a bit the order of the flavors to always go from newest to oldest
=> Add ubuntu 24.10 flavor

images/Dockerfile.ubuntu
because "[ -z ... ]` returns "1" and fails the build
Fixes #
=> Don't break docker build when /lib/modules etc are not found

.github/workflows/reusable-uki-test.yaml, .github/workflows/uki.yaml, .github/workflows/uki_branches.yaml
**What this PR does / why we need it**: 
Until the standard packages can be auto installed as sysext I think this gives a way to work with standard UKI images.  I can open a ticket on this for the future.  This will help me to build with the released file sets and test changes more quickly.
**Which issue(s) this PR fixes** 
Discussed at https://cloud-native.slack.com/archives/C0707M8UEU8/p1727801588480279?thread_ts=1727801588.480279&cid=C0707M8UEU8
I don't have a great way to set all of this without the full CI/CD access, so if someone has a few minutes to review before accepting that would be great.
I changed the logging filename to include the variant, so they do not overwrite.  I could not find anything this affects, but I might not have full visibility.
=> :robot: Build Ubuntu 24.04 Standard Image UKI on Github

.github/workflows/release.yaml
to make it easier to build UKI artifacts from it
Fixes #
=> Add systemd boot standard image to the build matrix

.github/workflows/reusable-uki-test.yaml, .github/workflows/uki.yaml
=> Add missing variant & k3s version to uki pipeline

.github/workflows/reusable-uki-test.yaml, .github/workflows/uki.yaml
It looks like during upgrade the resources for the VM can be exhausted
which kills the machine in the middle.
Now that we are running the UKI tests in our own workers we can increase
a bit the minimun resources for the test VMs.
This patch increases the memory to 6Gb from 4gb and the CPU from 2 to 4
Signed-off-by: Itxaka <itxaka@kairos.io>
=> 🤖 Increase the UKI VM resources

.github/workflows/image-arm-pr.yaml, .github/workflows/image-arm.yaml, .github/workflows/image-pr.yaml, .github/workflows/image.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-build-provider.yaml, .github/workflows/reusable-docker-arm-build.yaml, Earthfile
To a one that seems to not have requests limits in place which means we can drop the workarounds we have for the failure to download
Fixes #
=> :robot: Change trivy DB url

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
This adds the missing package on ubuntu and enables boot assesment services for UKI
Fixes #
=> :penguin: Enable boot assesment for UKI

Earthfile
https://github.com/kairos-io/AuroraBoot/pull/129
without this, the isos we generate will not allow any non-root user to login after installation
Fixes #
=> Bump auroraboot to v0.4.0 to fix root permission to 755

Earthfile
the push happens manually from a local build
It was removed here: https://github.com/kairos-io/kairos/pull/3055/files#diff-2705f6016a64189abd14041e2f3e8dbb829553295d9088e4eb42eccb5e61bf47R118
Fixes #
=> Use cached image again (now that we pushed 1.23)

images/Dockerfile.kairos, images/Dockerfile.kairos-alpine, images/Dockerfile.kairos-debian, images/Dockerfile.kairos-opensuse, images/Dockerfile.kairos-rhel, images/Dockerfile.kairos-ubuntu
because `echo` adds a LF (line feed) character and that breaks on Alpine
Fixes https://github.com/kairos-io/kairos/issues/3059
Fixes #
=> Create a truly empy /etc/machine-id

Earthfile
=> Downgrade kairos-agent by bumping framework

tests/provider_decentralized_test.go
This test is still run manually and fails later when it tries to upgrade to:
quay.io/kairos/kairos-opensuse:v1.0.0-rc2-k3sv1.21.14-k3s1
but I don't even know why it should be able to "upgrade" (actually downgrade) to such an old version successfully. Manually upgrading works.
This fix is meant to make it easier to run the test locally until we can run it again on CI (https://github.com/kairos-io/kairos/issues/2709).
Fixes #
=> Log files no longer have hardcoded names, use a glob for the test

.github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml, images/Dockerfile.kairos-ubuntu, images/Dockerfile.nvidia, images/Dockerfile.ubuntu
**What this PR does / why we need it**: This PR bumps the agx orin and nvidia image base to 22.04
Fixes #
=> feat(nvidia): bump base image to 22.04

.github/flavors.json, .github/workflows/image-arm-pr.yaml, .github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml, .github/workflows/release.yaml, Earthfile
also renames the jobs so they are easily identificable from the CI web
Fixes #
=> Push generic images on release and on master

Earthfile
Fix https://github.com/kairos-io/kairos/issues/3099
Fixes #
=> Bump sizes for orin

.github/workflows/release-arm.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-docker-arm-build.yaml
because we exceed github limit of 5000 results and it breaks the results page
Consumes @Itxaka 's amazing work here: https://github.com/Itxaka/sarif-filter
Part of: https://github.com/kairos-io/kairos/issues/3119
Fixes #
=> Keep only high and critical severity results

Earthfile
Because earthly injects binaries like earth_debugger which might container security vulnerabilities but are completely irrelevant to our image (and not included in it).
Fixes #
=> Scan images not dir

.github/workflows/reusable-docker-arm-build.yaml
Because standard/arm64 artifacts for v3.3.0 release are missing the k3s version.
e.g.
quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.3.0
Fixes #
=> Fix arm64 artifact naming missing k3s version

Earthfile, images/Dockerfile.kairos, images/Dockerfile.kairos-alpine, images/Dockerfile.kairos-debian, images/Dockerfile.kairos-opensuse, images/Dockerfile.kairos-rhel, images/Dockerfile.kairos-ubuntu
Bumps the version to one that handles k0s through the provider and allows passing of the software prefix and build version to create k0s images. By default it keeps the k3s functionality
=> Allow building of k0s images via earthly

Earthfile
From this:
```
quay.io/kairos/ubuntu:24.04-standard-amd64-generic-v3.3.1-rc2-2-g53b68481-k3sv1.32.1-rc2-k3sk3s1
```
to this:
```
quay.io/kairos/ubuntu:24.04-standard-amd64-generic-v3.3.1-rc2-2-g53b68481-k3sv1.32.1-rc2-k3s1
```
The bug was introduced here: https://github.com/kairos-io/kairos/commit/97872afeb
and it affects the names of the v3.3.1-rcX releases
Fixes #
=> Fix container image naming

.github/workflows/release.yaml
=> Try to avoid complicated logic to select k3s version

images/Dockerfile.kairos-ubuntu, images/Dockerfile.ubuntu
This is potentially dangerous for many reason, first of all it might compress firmwares that is not going to be picked up automatically by drivers which does not support compression. Some drivers, for example, may go looking directly for ucode or bin files without caring about compression.
Fixes #
=> fix(modules): do not compress modules

.github/workflows/reusable-docker-arm-build.yaml
and refactor steps
Fixes: https://github.com/kairos-io/kairos/issues/3167
Fixes #
=> Add the missing "v" in front of k3s version

.github/cleanup-old-images.sh, .github/upload-image-to-aws.sh, .github/workflows/upload-cloud-images.yaml
Fixes https://github.com/kairos-io/kairos/issues/3166
Fixes #
=> 3166 aws cleanup

.github/workflows/reusable-docker-arm-build.yaml, images/Dockerfile
Bump kairos-init to fix the nvidia build
On artifact push, use the same as the normal docker build but with push Use the proper Dockerfile
Pass the correct build args for the Kubernetes version Use the main dir as context
Fixes #
=> :robot: Fix master builds of arm64 artifacts

.github/workflows/image-master.yaml, .github/workflows/image-pr.yaml, .github/workflows/release.yaml, .github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-release.yaml, images/Dockerfile
fixes https://github.com/kairos-io/kairos/issues/3157
=> Add k0s artifacts

examples/builds/ubuntu-fips/Dockerfile
We dont support automatic fips for ubuntu so we should not pass that flag and show in the example how to build a ubutu fips image
Fixes #
=> Disable fips flag for ubnutu example

.github/workflows/upload-cloud-images.yaml
because if we have released 3.4.0-beta1 and we then push 3.3.3 that release will never be pushed because the scheduled job only picks the latest tag from master.
Fixes #
=> Push cloud images when a new tag is created

.github/public-cloud/cleanup-old-images-aws.sh, .github/public-cloud/cleanup-old-images-azure.sh, .github/public-cloud/cleanup-old-images-gcp.sh, .github/public-cloud/test-aws-image.sh, .github/public-cloud/upload-image-to-aws.sh
Part of https://github.com/kairos-io/kairos/issues/3175
- Fixes cleanup script that didn't properly split the versions
- Treats beta,alpha,pre and others as non-stable (not just "rc")
- Tests the aws AMI before copying it to other regions or making it public
=> 3175 add AWS smoke test

tests/bundles_test.go
Now that we enable the same sysext paths for everything we rely in the profile.d setting an enviroment variable to set the sysext paths.
Runnig commands related to sysext service via ssh without a real login does not load any profile files so that env var is not set and it defaults to the normal one which makes it seem like there is no extensions in the system
This changes it so it runs the login for the command so it loads the proper env
Fixes #
=> bug: Fix bundle tests

.github/workflows/reusable-build-flavor.yaml
Fixed the nvidia orin.
As init doesnt have the full set of packages for orin, we still need to build the base image as a separate thing, then use that as base for init to built the kairos image, which means that the base image does not confoft to what we are expecting as input, which breaks our distro/version separation.
We fix this by fixing the distro and tag manually in the nvidia build  case
=> Fix the nvidia orin build on master

.github/workflows/reusable-qemu-test.yaml, tests/provider_decentralized_test.go
- Run it under the github provided nodes as it seems that our workers network is not good enough
- Also rework the config so it enables k3s and sets a proper hostname rather than a random one, as that was causing on reboot the k3s nodes to have a different names and rebuild themselves, which is slower
- Drop the upgrade part as that its covered in a diferent test,here we are checking for decentralized communication and k3s setup
Fixes #
=> Fix decentralized test

.grype.yaml, grype.yaml
grype is not that good on kernel info and uses a database that does not match the real score of the distributions. In some cases, grype reports a 9.1 score while the distribution gave it a 5.4 and didnt consider fixing it because its not that high priority or almost impossible to exploit.
so we are stuck with grype stopping the release while there are no plans on fixing those.
There is some other times that its totally out of our control and probably not even affecting them, like the k3s http golang vuln which is probably not possible on k3s but its being reported as critical.
This is only a workaround but we should probably think about dropping grype if it requires this much handholding and we have to keep adding entries to the ignore becuase its just not good enough.
**What this PR does …
=> Add grype ignore file

.github/workflows/image-master.yaml, .github/workflows/image-pr.yaml
Now that there is an alpine 3.21 release, we no longer need the upgrade job to use a release matcher to match the previous release as it will match with 3.21 so we can remove the exclude and just run the job as the others
Fixes #
=> Remove upgrade alpine exclude test

.github/workflows/reusable-release.yaml
By mistake the v was clean off but our artifacts all have the v in front of the k8s provider version
Fixes #
=> Keep the v in the kubernetes version

.github/workflows/reusable-release.yaml
downloads on the homepage cannot find the artifact because the missing `-` between kairos version and k8s version
=> Add missing concatenation to release artifact name

examples/cloud-configs/wifi-alpine.yaml
Remove need for manually generating WiFI config on a working system and then copying into cloud-config. Now you can just add your WiFi network details and it will connect on first boot
=> Improve Alpine WiFi example

.github/workflows/stale.yaml
tweaks stale bot arguments so we don't get overwhelmed
Fixes #
=> ci: run stale bot on unconfirmed issues/PRs

examples/builds/fedora-fips/Dockerfile, examples/builds/rockylinux-fips/Dockerfile, examples/builds/ubuntu-20.04-fips/Dockerfile, examples/builds/ubuntu-22.04-fips/Dockerfile, examples/builds/ubuntu-non-hwe/Dockerfile, images/Dockerfile
This PR changes how the kairos-init is made available during the build, instead copying it and bloat the image size it just mounts it during the RUN command, saving up ~100MB on each image build.
Fixes #
=> Mount kairos-init instead of copying during image build

tests/tests_suite_test.go, tests/upgrade_cli_test.go, tests/upgrade_latest_cli_test.go
Fixes https://github.com/kairos-io/kairos/issues/3374
Fixes #
=> Check that the ssh host fingerprint hasn't changed after upgrade

.github/workflows/reusable-build-flavor.yaml, .github/workflows/reusable-release.yaml, .github/workflows/reusable-uki-test.yaml, .github/workflows/upload-cloud-images.yaml, renovate.json
It brings flag changes for UKI
Part of https://github.com/kairos-io/kairos/issues/3222
=> Bump aurora 0.9.0 for uki
